// Code generated by goctl. DO NOT EDIT.
// Source: payment.proto

package server

import (
	"context"

	"gitee.com/zhuyunkj/pay-gateway/rpc/internal/logic"
	"gitee.com/zhuyunkj/pay-gateway/rpc/internal/svc"
	"gitee.com/zhuyunkj/pay-gateway/rpc/pb/pb"
)

type PaymentServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedPaymentServer
}

func NewPaymentServer(svcCtx *svc.ServiceContext) *PaymentServer {
	return &PaymentServer{
		svcCtx: svcCtx,
	}
}

// 创建支付订单
func (s *PaymentServer) OrderPay(ctx context.Context, in *pb.OrderPayReq) (*pb.OrderPayResp, error) {
	l := logic.NewOrderPayLogic(ctx, s.svcCtx)
	return l.OrderPay(in)
}

// 关闭订单
func (s *PaymentServer) ClosePayOrder(ctx context.Context, in *pb.ClosePayOrderReq) (*pb.Empty, error) {
	l := logic.NewClosePayOrderLogic(ctx, s.svcCtx)
	return l.ClosePayOrder(in)
}

// 支付宝转出
func (s *PaymentServer) AlipayFundTransUniTransfer(ctx context.Context, in *pb.AlipayFundTransUniTransferReq) (*pb.Empty, error) {
	l := logic.NewAlipayFundTransUniTransferLogic(ctx, s.svcCtx)
	return l.AlipayFundTransUniTransfer(in)
}

// 查询订单
func (s *PaymentServer) OrderStatus(ctx context.Context, in *pb.OrderStatusReq) (*pb.OrderStatusResp, error) {
	l := logic.NewOrderStatusLogic(ctx, s.svcCtx)
	return l.OrderStatus(in)
}

// 支付宝转出账号校验
func (s *PaymentServer) AlipayCheckAccount(ctx context.Context, in *pb.AlipayCheckAccountReq) (*pb.AlipayCheckAccountResp, error) {
	l := logic.NewAlipayCheckAccountLogic(ctx, s.svcCtx)
	return l.AlipayCheckAccount(in)
}

// 抖音退款订单
func (s *PaymentServer) DyOrderRefund(ctx context.Context, in *pb.DyOrderRefundReq) (*pb.DyOrderRefundResp, error) {
	l := logic.NewDyOrderRefundLogic(ctx, s.svcCtx)
	return l.DyOrderRefund(in)
}

// 抖音退款 使用通用交易系统
func (s *PaymentServer) CreateDouyinRefund(ctx context.Context, in *pb.CreateDouyinRefundReq) (*pb.CreateDouyinRefundResp, error) {
	l := logic.NewCreateDouyinRefundLogic(ctx, s.svcCtx)
	return l.CreateDouyinRefund(in)
}

// 支付宝：创建支付
func (s *PaymentServer) AlipayTrade(ctx context.Context, in *pb.AlipayTradeReq) (*pb.AlipayPageSignResp, error) {
	l := logic.NewAlipayTradeLogic(ctx, s.svcCtx)
	return l.AlipayTrade(in)
}

// 支付宝：支付并签约
func (s *PaymentServer) AlipayPagePayAndSign(ctx context.Context, in *pb.AlipayPageSignReq) (*pb.AlipayPageSignResp, error) {
	l := logic.NewAlipayPagePayAndSignLogic(ctx, s.svcCtx)
	return l.AlipayPagePayAndSign(in)
}

// 支付宝新的充值订阅 可以选择不同的支付宝账号：支付并签约
func (s *PaymentServer) AlipayPagePayAndSignChoiceAccount(ctx context.Context, in *pb.AlipayPageSignReq) (*pb.AlipayPageSignResp, error) {
	l := logic.NewAlipayPagePayAndSignChoiceAccountLogic(ctx, s.svcCtx)
	return l.AlipayPagePayAndSignChoiceAccount(in)
}

// 支付宝：解约
func (s *PaymentServer) AlipayPageUnSign(ctx context.Context, in *pb.AlipayPageUnSignReq) (*pb.AlipayCommonResp, error) {
	l := logic.NewAlipayPageUnSignLogic(ctx, s.svcCtx)
	return l.AlipayPageUnSign(in)
}

// 支付宝：创建退款订单
func (s *PaymentServer) AlipayCreateRefund(ctx context.Context, in *pb.AlipayRefundReq) (*pb.CreateRefundResp, error) {
	l := logic.NewAlipayCreateRefundLogic(ctx, s.svcCtx)
	return l.AlipayCreateRefund(in)
}

// 支付宝：退款
func (s *PaymentServer) AlipayRefund(ctx context.Context, in *pb.AlipayRefundReq) (*pb.AliRefundResp, error) {
	l := logic.NewAlipayRefundLogic(ctx, s.svcCtx)
	return l.AlipayRefund(in)
}

// 支付宝：订阅扣款
func (s *PaymentServer) AlipayTradePay(ctx context.Context, in *pb.AlipayTradePayReq) (*pb.AlipayCommonResp, error) {
	l := logic.NewAlipayTradePayLogic(ctx, s.svcCtx)
	return l.AlipayTradePay(in)
}

// 支付宝：签约延期
func (s *PaymentServer) AlipayAgreementModify(ctx context.Context, in *pb.AlipayAgreementModifyReq) (*pb.AlipayCommonResp, error) {
	l := logic.NewAlipayAgreementModifyLogic(ctx, s.svcCtx)
	return l.AlipayAgreementModify(in)
}

// 微信统一下单接口，JSAPI，对接文档：https://pay.weixin.qq.com/docs/merchant/products/jsapi-payment/introduction.html
func (s *PaymentServer) WechatUnifiedOrder(ctx context.Context, in *pb.AlipayPageSignReq) (*pb.WxUnifiedPayReply, error) {
	l := logic.NewWechatUnifiedOrderLogic(ctx, s.svcCtx)
	return l.WechatUnifiedOrder(in)
}

// 微信统一支付退款
func (s *PaymentServer) WechatRefundOrder(ctx context.Context, in *pb.WechatRefundOrderReq) (*pb.CreateRefundResp, error) {
	l := logic.NewWechatRefundOrderLogic(ctx, s.svcCtx)
	return l.WechatRefundOrder(in)
}

// 微信h5支付，对接文档：https://pay.weixin.qq.com/docs/merchant/apis/h5-payment/direct-jsons/h5-prepay.html
func (s *PaymentServer) WechatPayH5Order(ctx context.Context, in *pb.AlipayPageSignReq) (*pb.WxH5PayReplay, error) {
	l := logic.NewWechatPayH5OrderLogic(ctx, s.svcCtx)
	return l.WechatPayH5Order(in)
}

// 绑定订单号和华为购买token
func (s *PaymentServer) BindHuaweiPayData(ctx context.Context, in *pb.BindHuaweiPayDataReq) (*pb.BindHuaweiPayDataResp, error) {
	l := logic.NewBindHuaweiPayDataLogic(ctx, s.svcCtx)
	return l.BindHuaweiPayData(in)
}

// 用户主动解除华为订阅
func (s *PaymentServer) UnsubscribeHuawei(ctx context.Context, in *pb.UnsubscribeHuaweiReq) (*pb.UnsubscribeHuaweiResp, error) {
	l := logic.NewUnsubscribeHuaweiLogic(ctx, s.svcCtx)
	return l.UnsubscribeHuawei(in)
}

// 抖音周期代扣相关查询和修改
func (s *PaymentServer) DouyinPeriodOrder(ctx context.Context, in *pb.DouyinPeriodOrderReq) (*pb.DouyinPeriodOrderResp, error) {
	l := logic.NewDouyinPeriodOrderLogic(ctx, s.svcCtx)
	return l.DouyinPeriodOrder(in)
}
