// Code generated by goctl. DO NOT EDIT!
// Source: payment.proto

package server

import (
	"context"

	"gitee.com/zhuyunkj/pay-gateway/internal/logic"
	"gitee.com/zhuyunkj/pay-gateway/internal/svc"
	"gitee.com/zhuyunkj/pay-gateway/pb/pb"
)

type PaymentServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedPaymentServer
}

func NewPaymentServer(svcCtx *svc.ServiceContext) *PaymentServer {
	return &PaymentServer{
		svcCtx: svcCtx,
	}
}

// 创建支付订单
func (s *PaymentServer) OrderPay(ctx context.Context, in *pb.OrderPayReq) (*pb.OrderPayResp, error) {
	l := logic.NewOrderPayLogic(ctx, s.svcCtx)
	return l.OrderPay(in)
}
