// Code generated by goctl. DO NOT EDIT.
package types

type CommonHeader struct {
	Brand      string `header:"Brand,optional"`
	AppOrigin  string `header:"App-Origin,optional"`
	AppVersion string `header:"App-Version,optional"`
	SdkVersion string `header:"Sdk-Version,optional"`
	DeviceId   string `header:"Device-Id,optional"`
	Token      string `header:"Token,optional"`
	IMEI       string `header:"IMEI,optional"`
}

type HeaderReq struct {
	CommonHeader
	UserId        int    `header:"UserId,optional"`
	OldDeviceId   string `header:"NativeDeviceId,optional"`
	Xsign         string `header:"Xsign,optional"`
	XForwardedFor string `header:"X-Forwarded-For,optional"`
	Remoteip      string `header:"Remoteip,optional"`
	RandomId      int    `json:"random_id,optional"`
}

type ResultResp struct {
	RequestId string      `json:"RequestId"`
	Status    int64       `json:"STATUS"`
	Desc      string      `json:"DESC"`
	Data      interface{} `json:"DATA"`
}

type EmptyReq struct {
}

type SupplementaryOrdersReq struct {
	Type        string `form:"type"`
	StartMinute string `form:"startMinute""`
	EndMinute   string `form:"endMinute"`
	IsNotice    string `form:"isNotice"`
}

type SupplementaryOrdersResp struct {
	ErrNo   int    `json:"err_no"`
	ErrTips string `json:"err_tips"`
}

type CrtUploadReq struct {
	AlipayAppCertPublicKeyPath string `form:"alipayAppCertPublicKeyPath,optional"`
	AlipayPublicKeyPath        string `form:"alipayPublicKeyPath,optional"`
	AlipayPayRootCertPath      string `form:"alipayPayRootCertPath,optional"`
	WeChatPayPrivateKey        string `form:"weChatPayPrivateKey, optional"`
}

type AlipayFundTransUniTransferReq struct {
	OrderNo     string `json:"order_no"`     //商户唯一订单号
	OrderTitle  string `json:"order_title"`  //转账标题
	TransAmount string `json:"trans_amount"` //订单总金额 [0.1,100]
	PayAccount  string `json:"pay_account"`  //收款方账户
	PayName     string `json:"pay_name"`     //收款方真实姓名
	Remark      string `json:"remark"`       //转账备注
	PkgName     string `json:"pkg_name"`     //包名
}

type AlipayPageSignReq struct {
	PkgName     string `json:"pkg_name"`     //包名
	OrderNo     string `json:"order_no"`     //商户唯一订单号
	OrderTitle  string `json:"order_title"`  //转账标题
	TransAmount string `json:"trans_amount"` //订单总金额 [0.1,100]
	PayAccount  string `json:"pay_account"`  //收款方账户
	PayName     string `json:"pay_name"`     //收款方真实姓名
	PeriodType  string `json:"period_type"`  //周期类型
}

type RefundReq struct {
	OutTradeRefundNo string `json:"order_title"`      //
	Status           int    `json:"status"`           // 操作，1通过，2拒绝
	Reviewer         string `json:"reviewer"`         // 操作者
	ReviewerComment  string `json:"reviewer_comment"` // 操作者备注
}

type ComplainReq struct {
	AppId     string `json:"app_id"`
	StartTime string `json:"start_time"`
	EndTime   string `json:"end_time"`
}

type ByteDanceReq struct {
	Timestamp    string `json:"timestamp,optional"`
	Nonce        string `json:"nonce,optional"`
	Msg          string `json:"msg,optional"`
	Type         string `json:"type,optional"`
	MsgSignature string `json:"msg_signature,optional"`
}

type ByteDanceResp struct {
	ErrNo   int    `json:"err_no"`
	ErrTips string `json:"err_tips"`
}

type WeChatResp struct {
	Code    string `json:"code,optional"`
	Message string `json:"message,optional"`
}

type WeChatUnifiedResp struct {
	ReturnCode string `json:"return_code,optional"`
	ReturnMsg  string `json:"return_msg,optional"`
}

type KsResp struct {
	Result    int    `json:"result"`     //1-成功，其他-失败。失败小程序平台会尝试重推此消息
	MessageId string `json:"message_id"` //当前消息的message_id
}

type Resource struct {
	OriginalType   string `json:"original_type"`
	Algorithm      string `json:"algorithm"`
	Ciphertext     string `json:"ciphertext"`
	AssociatedData string `json:"associated_data"`
	Nonce          string `json:"nonce"`
}

type WechatRefundReq struct {
	OutTradeNo   string   `path:"OutTradeNo,optional"`
	EventType    string   `json:"event_type"`
	Id           string   `json:"id"`
	CreateTime   string   `json:"create_time"`
	ResourceType string   `json:"resource_type"`
	Summary      string   `json:"summary"`
	Resource     Resource `json:"resource"`
}

type WechatNotifyH5Req struct {
	AppID        string   `path:"AppID,optional"` // 微信支付appid
	Id           string   `json:"id"`             // 通知的唯一ID
	CreateTime   string   `json:"create_time"`    // 通知创建的时间，遵循rfc3339标准格式，格式为yyyy-MM-DDTHH:mm:ss+TIMEZONE，yyyy-MM-DD表示年月日，T出现在字符串中，表示time元素的开头，HH:mm:ss.表示时分秒，TIMEZONE表示时区（+08:00表示东八区时间，领先UTC 8小时，即北京时间）。例如：2015-05-20T13:29:35+08:00表示北京时间2015年05月20日13点29分35秒。
	EventType    string   `json:"event_type"`     // 通知的类型，支付成功通知的类型为TRANSACTION.SUCCESS。
	ResourceType string   `json:"resource_type"`  // 通知的资源数据类型，支付成功通知为encrypt-resource。
	Resource     Resource `json:"resource"`       // 通知资源数据。
	Summary      string   `json:"summary"`        // 回调摘要
}

type DouyinReq struct {
	Version       string `json:"version,optional"`
	Type          string `json:"type,optional"`
	Msg           string `json:"msg,optional"`
	ByteTimestamp string `header:"Byte-Timestamp"`
	ByteNonceStr  string `header:"Byte-Nonce-Str"`
	ByteSignature string `header:"Byte-Signature"`
	Body          string `json:"body"`
}

type DouyinResp struct {
	ErrNo   int    `json:"err_no"`
	ErrTips string `json:"err_tips"`
}

type HuaweiReq struct {
	Version           string            `json:"version,optional"`       // 通知版本。
	NotifyTime        int64             `json:"notifyTime,optional"`    // 通知时间，UTC时间戳，即自1970年1月1日0时起到商户通知的毫秒数。
	EventType         string            `json:"eventType,optional"`     // 通知类型，取值如下：ORDER：订单 SUBSCRIPTION：订阅
	ApplicationId     string            `json:"applicationId,optional"` // 应用ID
	OrderNotification OrderNotification `json:"orderNotification"`      // 订单通知内容，eventType为ORDER时返回
	SubNotification   SubNotification   `json:"subNotification"`        // 订阅通知内容，eventType为SUBSCRIPTION时返回。
}

type OrderNotification struct {
	Version          string `json:"version,optional"`          // 通知版本
	NotificationType int    `json:"notificationType,optional"` // 通知事件的类型，取值如下：1：支付成功 2：退款成功
	PurchaseToken    string `json:"purchaseToken,optional"`    // 待下发商品的购买Token, 支付后拿到的最新的purchaseToken，表示该商品和该用户的对应关系
	ProductId        string `json:"productId,optional"`        // 商品ID
}

type SubNotification struct {
	Version                  string `json:"version,optional"`                  // 通知版本
	StatusUpdateNotification string `json:"statusUpdateNotification,optional"` // 通知消息，格式为JSON字符串，请参见statusUpdateNotification。
	NotificationSignature    string `json:"notificationSignature,optional"`    // 对statusUpdateNotification字段的签名字符串，签名算法为signatureAlgorithm表示的签名算法。您的服务器在收到签名字符串后，需要参见对返回结果验签使用IAP公钥对statusUpdateNotification的JSON字符串进行验签。公钥获取请参见查询支付服务信息。
	SignatureAlgorithm       string `json:"signatureAlgorithm,optional"`       // 签名算法
}

type StatusUpdateNotification struct {
	Environment                       string `json:"environment"`                       // 发送通知的环境。PROD：正式环境 Sandbox：沙盒测试
	NotificationType                  int    `json:"notificationType"`                  // 通知事件的类型
	SubscriptionId                    string `json:"subscriptionId"`                    // 订阅ID
	PurchaseToken                     string `json:"purchaseToken"`                     // 订阅token，与上述订阅ID字段subscriptionId对应
	CancellationDate                  int64  `json:"cancellationDate"`                  // 撤销订阅时间或退款时间，UTC时间戳，以毫秒为单位，仅在notificationType取值为CANCEL的场景下会传入。
	OrderId                           string `json:"orderId"`                           // 订单ID，唯一标识一笔需要收费的收据，由华为应用内支付服务器在创建订单以及订阅型商品续费时生成。每一笔新的收据都会使用不同的orderId。通知类型为NEW_RENEWAL_PREF时不存在。
	LatestReceipt                     string `json:"latestReceipt"`                     // 最近的一笔收据的token，仅在notificationType取值为INITIAL_BUY 、RENEWAL或INTERACTIVE_RENEWAL并且续期成功情况下传入
	LatestReceiptInfo                 string `json:"latestReceiptInfo"`                 // 最近的一笔收据，JSON字符串格式，包含的参数请参见InappPurchaseDetails，在notificationType取值为CANCEL时无值
	LatestReceiptInfoSignature        string `json:"latestReceiptInfoSignature"`        // 对latestReceiptInfo的签名字符串，签名算法为statusUpdateNotification中的signatureAlgorithm。您的服务器在收到签名字符串后，需要参见对返回结果验签使用IAP公钥对latestReceiptInfo的JSON字符串进行验签。公钥获取请参见查询支付服务信息。
	LatestExpiredReceipt              string `json:"latestExpiredReceipt"`              // 最近的一笔过期收据的token
	LatestExpiredReceiptInfo          string `json:"atestExpiredReceiptInfo"`           // 最近的一笔过期收据，JSON字符串格式，在notificationType取值为RENEWAL或INTERACTIVE_RENEWAL时有值
	LatestExpiredReceiptInfoSignature string `json:"latestExpiredReceiptInfoSignature"` // 对latestExpiredReceiptInfo的签名字符串，签名算法为statusUpdateNotification中的signatureAlgorithm。您的服务器在收到签名字符串后，需要参见对返回结果验签使用IAP公钥对latestExpiredReceiptInfo的JSON字符串进行验签。
	SignatureAlgorithm                string `json:"signatureAlgorithm"`                // 签名算法
	AutoRenewStatus                   int    `json:"autoRenewStatus"`                   // 续期状态。取值说明：1：当前周期到期后正常续期 0：用户已终止续期
	RefundPayOrderId                  string `json:"refundPayOrderId"`                  // 退款交易号，在notificationType取值为CANCEL时有值
	ProductId                         string `json:"productId"`                         // 订阅型商品ID
	ApplicationId                     string `json:"applicationId"`                     // 应用ID
	ExpirationIntent                  int    `json:"expirationIntent"`                  // 超期原因，仅在notificationType为RENEWAL或INTERACTIVE_RENEWAL时并且续期失败情况下有值
}

type HuaweiResp struct {
}
