// Code generated by goctl. DO NOT EDIT.
package types

type ResultResp struct {
	RequestId string      `json:"RequestId"`
	Status    int64       `json:"STATUS"`
	Desc      string      `json:"DESC"`
	Data      interface{} `json:"DATA"`
}

type EmptyReq struct {
}

type ByteDanceReq struct {
	Timestamp    string `json:"timestamp,optional"`
	Nonce        string `json:"nonce,optional"`
	Msg          string `json:"msg,optional"`
	Type         string `json:"type,optional"`
	MsgSignature string `json:"msg_signature,optional"`
}

type ByteDanceResp struct {
	ErrNo   int    `json:"err_no"`
	ErrTips string `json:"err_tips"`
}

type WeChatResp struct {
	Code    string `json:"code,optional"`
	Message string `json:"message,optional"`
}

type CrtUploadReq struct {
	AlipayAppCertPublicKeyPath string `form:"alipayAppCertPublicKeyPath,optional"`
	AlipayPublicKeyPath        string `form:"alipayPublicKeyPath,optional"`
	AlipayPayRootCertPath      string `form:"alipayPayRootCertPath,optional"`
	WeChatPayPrivateKey        string `form:"weChatPayPrivateKey, optional"`
}
