// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	inter "gitee.com/zhuyunkj/pay-gateway/api/internal/handler/inter"
	notify "gitee.com/zhuyunkj/pay-gateway/api/internal/handler/notify"
	"gitee.com/zhuyunkj/pay-gateway/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/notify/wechat",
				Handler: notify.NotifyWechatHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/notify/bytedance",
				Handler: notify.NotifyBytedanceHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Inter},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/internal/crt/upload",
					Handler: inter.CrtUploadHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/internal/getPayNodeList",
					Handler: inter.GetPayNodeListHandler(serverCtx),
				},
			}...,
		),
	)
}
