// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	crontab "gitlab.muchcloud.com/consumer-project/pay-gateway/api/internal/handler/crontab"
	health "gitlab.muchcloud.com/consumer-project/pay-gateway/api/internal/handler/health"
	inter "gitlab.muchcloud.com/consumer-project/pay-gateway/api/internal/handler/inter"
	notify "gitlab.muchcloud.com/consumer-project/pay-gateway/api/internal/handler/notify"
	"gitlab.muchcloud.com/consumer-project/pay-gateway/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/ver/health/check",
				Handler: health.HealthCheckHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/notify/wechat",
				Handler: notify.NotifyWechatHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/notify/bytedance",
				Handler: notify.NotifyBytedanceHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/notify/alipay",
				Handler: notify.NotifyAlipayHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/notify/kspay",
				Handler: notify.NotifyKspayHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/notify/alipayNew",
				Handler: notify.NotifyAlipayNewHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/notify/alipayNew/sign",
				Handler: notify.NotifyAlipaySignHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/notify/unified/wechat",
				Handler: notify.NotifyWechatUnifiedOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/notify/refund/wechat/:OutTradeNo",
				Handler: notify.NotifyWechatRefundOrderHandler(serverCtx),
			},
			{
				// 小程序业务-微信商户退款回调通知
				Method:  http.MethodPost,
				Path:    "/notify/refund/wechatMini/:OutRefundNo",
				Handler: notify.NotifyRefundWechatMiniHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/notify/h5/wechat/:AppID",
				Handler: notify.NotifyWechatH5OrderHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/notify/douyin",
				Handler: notify.NotifyDouyinHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/notify/huawei",
				Handler: notify.NotifyHuaweiHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Inter},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/internal/crt/upload",
					Handler: inter.CrtUploadHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/internal/getPayNodeList",
					Handler: inter.GetPayNodeListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/internal/alipayFundTransUniTransfer",
					Handler: inter.AlipayFundTransUniTransferHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/internal/handleRefund",
					Handler: inter.HandleRefundHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/internal/complain",
				Handler: inter.HandleComplainHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/internal/paySubscribeMoney",
				Handler: inter.HandlePaySubscribeMoneyHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/crontab/supplementaryOrders",
				Handler: crontab.SupplementaryOrdersHandler(serverCtx),
			},
		},
	)
}
