// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: payment.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//支付方式枚举
type PayType int32

const (
	PayType_AlipayWap PayType = 0 //支付宝wap支付
	PayType_WxUniApp  PayType = 1 //微信小程序支付
	PayType_TiktokEc  PayType = 2 //头条小程序支付
)

// Enum value maps for PayType.
var (
	PayType_name = map[int32]string{
		0: "AlipayWap",
		1: "WxUniApp",
		2: "TiktokEc",
	}
	PayType_value = map[string]int32{
		"AlipayWap": 0,
		"WxUniApp":  1,
		"TiktokEc":  2,
	}
)

func (x PayType) Enum() *PayType {
	p := new(PayType)
	*p = x
	return p
}

func (x PayType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PayType) Descriptor() protoreflect.EnumDescriptor {
	return file_payment_proto_enumTypes[0].Descriptor()
}

func (PayType) Type() protoreflect.EnumType {
	return &file_payment_proto_enumTypes[0]
}

func (x PayType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PayType.Descriptor instead.
func (PayType) EnumDescriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{0}
}

//创建支付订单
type OrderPayReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppPkgName string  `protobuf:"bytes,1,opt,name=AppPkgName,proto3" json:"AppPkgName,omitempty"`                 //应用包名
	OrderSn    string  `protobuf:"bytes,2,opt,name=OrderSn,proto3" json:"OrderSn,omitempty"`                       //唯一订单号
	Amount     int64   `protobuf:"varint,3,opt,name=Amount,proto3" json:"Amount,omitempty"`                        //订单金额，单位分
	Subject    string  `protobuf:"bytes,4,opt,name=Subject,proto3" json:"Subject,omitempty"`                       //订单标题
	PayType    PayType `protobuf:"varint,5,opt,name=PayType,proto3,enum=payment.PayType" json:"PayType,omitempty"` //支付方式
	NotifyURL  string  `protobuf:"bytes,6,opt,name=NotifyURL,proto3" json:"NotifyURL,omitempty"`                   //回调通知地址
	ReturnURL  string  `protobuf:"bytes,7,opt,name=returnURL,proto3" json:"returnURL,omitempty"`                   //H5,wap支付跳转地址
	WxOpenID   string  `protobuf:"bytes,8,opt,name=WxOpenID,proto3" json:"WxOpenID,omitempty"`                     //微信小程序支付openid
}

func (x *OrderPayReq) Reset() {
	*x = OrderPayReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payment_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderPayReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderPayReq) ProtoMessage() {}

func (x *OrderPayReq) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderPayReq.ProtoReflect.Descriptor instead.
func (*OrderPayReq) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{0}
}

func (x *OrderPayReq) GetAppPkgName() string {
	if x != nil {
		return x.AppPkgName
	}
	return ""
}

func (x *OrderPayReq) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *OrderPayReq) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *OrderPayReq) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *OrderPayReq) GetPayType() PayType {
	if x != nil {
		return x.PayType
	}
	return PayType_AlipayWap
}

func (x *OrderPayReq) GetNotifyURL() string {
	if x != nil {
		return x.NotifyURL
	}
	return ""
}

func (x *OrderPayReq) GetReturnURL() string {
	if x != nil {
		return x.ReturnURL
	}
	return ""
}

func (x *OrderPayReq) GetWxOpenID() string {
	if x != nil {
		return x.WxOpenID
	}
	return ""
}

//创建支付订单返回
type OrderPayResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderSn   string            `protobuf:"bytes,1,opt,name=OrderSn,proto3" json:"OrderSn,omitempty"`                       //唯一订单号
	TradeNo   string            `protobuf:"bytes,2,opt,name=TradeNo,proto3" json:"TradeNo,omitempty"`                       //流水号
	PayType   PayType           `protobuf:"varint,6,opt,name=PayType,proto3,enum=payment.PayType" json:"PayType,omitempty"` //支付方式
	AlipayWap string            `protobuf:"bytes,3,opt,name=AlipayWap,proto3" json:"AlipayWap,omitempty"`                   //支付宝wap支付
	WxUniApp  *WxUniAppPayReply `protobuf:"bytes,4,opt,name=WxUniApp,proto3" json:"WxUniApp,omitempty"`                     //微信小程序支付
	TikTokEc  *TiktokEcPayReply `protobuf:"bytes,5,opt,name=TikTokEc,proto3" json:"TikTokEc,omitempty"`                     //抖音小程序支付
}

func (x *OrderPayResp) Reset() {
	*x = OrderPayResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payment_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderPayResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderPayResp) ProtoMessage() {}

func (x *OrderPayResp) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderPayResp.ProtoReflect.Descriptor instead.
func (*OrderPayResp) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{1}
}

func (x *OrderPayResp) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *OrderPayResp) GetTradeNo() string {
	if x != nil {
		return x.TradeNo
	}
	return ""
}

func (x *OrderPayResp) GetPayType() PayType {
	if x != nil {
		return x.PayType
	}
	return PayType_AlipayWap
}

func (x *OrderPayResp) GetAlipayWap() string {
	if x != nil {
		return x.AlipayWap
	}
	return ""
}

func (x *OrderPayResp) GetWxUniApp() *WxUniAppPayReply {
	if x != nil {
		return x.WxUniApp
	}
	return nil
}

func (x *OrderPayResp) GetTikTokEc() *TiktokEcPayReply {
	if x != nil {
		return x.TikTokEc
	}
	return nil
}

//微信uniapp支付返回
type WxUniAppPayReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderInfo string `protobuf:"bytes,1,opt,name=OrderInfo,proto3" json:"OrderInfo,omitempty"` //订单信息的json
	TimeStamp string `protobuf:"bytes,2,opt,name=TimeStamp,proto3" json:"TimeStamp,omitempty"` //生成订单时间
	NonceStr  string `protobuf:"bytes,3,opt,name=NonceStr,proto3" json:"NonceStr,omitempty"`   //用于验签的随机串
	Package   string `protobuf:"bytes,4,opt,name=Package,proto3" json:"Package,omitempty"`     //"prepay_id="+预支付交易会话标识
	SignType  string `protobuf:"bytes,5,opt,name=SignType,proto3" json:"SignType,omitempty"`   //签名方式
	PaySign   string `protobuf:"bytes,6,opt,name=PaySign,proto3" json:"PaySign,omitempty"`     //支付签名
	OrderSn   string `protobuf:"bytes,7,opt,name=OrderSn,proto3" json:"OrderSn,omitempty"`     //商户订单号
}

func (x *WxUniAppPayReply) Reset() {
	*x = WxUniAppPayReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payment_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WxUniAppPayReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WxUniAppPayReply) ProtoMessage() {}

func (x *WxUniAppPayReply) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WxUniAppPayReply.ProtoReflect.Descriptor instead.
func (*WxUniAppPayReply) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{2}
}

func (x *WxUniAppPayReply) GetOrderInfo() string {
	if x != nil {
		return x.OrderInfo
	}
	return ""
}

func (x *WxUniAppPayReply) GetTimeStamp() string {
	if x != nil {
		return x.TimeStamp
	}
	return ""
}

func (x *WxUniAppPayReply) GetNonceStr() string {
	if x != nil {
		return x.NonceStr
	}
	return ""
}

func (x *WxUniAppPayReply) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *WxUniAppPayReply) GetSignType() string {
	if x != nil {
		return x.SignType
	}
	return ""
}

func (x *WxUniAppPayReply) GetPaySign() string {
	if x != nil {
		return x.PaySign
	}
	return ""
}

func (x *WxUniAppPayReply) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

//抖音小程序支付返回
type TiktokEcPayReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId    string `protobuf:"bytes,1,opt,name=OrderId,proto3" json:"OrderId,omitempty"`       //抖音侧唯一订单号
	OrderToken string `protobuf:"bytes,2,opt,name=OrderToken,proto3" json:"OrderToken,omitempty"` //签名后的订单信息
}

func (x *TiktokEcPayReply) Reset() {
	*x = TiktokEcPayReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payment_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TiktokEcPayReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TiktokEcPayReply) ProtoMessage() {}

func (x *TiktokEcPayReply) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TiktokEcPayReply.ProtoReflect.Descriptor instead.
func (*TiktokEcPayReply) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{3}
}

func (x *TiktokEcPayReply) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *TiktokEcPayReply) GetOrderToken() string {
	if x != nil {
		return x.OrderToken
	}
	return ""
}

var File_payment_proto protoreflect.FileDescriptor

var file_payment_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0xfd, 0x01, 0x0a, 0x0b, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x50, 0x61, 0x79, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x41, 0x70, 0x70, 0x50,
	0x6b, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x41, 0x70,
	0x70, 0x50, 0x6b, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x53, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x53, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x75,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x53, 0x75, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x12, 0x2a, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e,
	0x50, 0x61, 0x79, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x50, 0x61, 0x79, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x55, 0x52, 0x4c, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x55, 0x52, 0x4c, 0x12, 0x1c,
	0x0a, 0x09, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x55, 0x52, 0x4c, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x55, 0x52, 0x4c, 0x12, 0x1a, 0x0a, 0x08,
	0x57, 0x78, 0x4f, 0x70, 0x65, 0x6e, 0x49, 0x44, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x57, 0x78, 0x4f, 0x70, 0x65, 0x6e, 0x49, 0x44, 0x22, 0xfa, 0x01, 0x0a, 0x0c, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x50, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x53, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x53, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x54, 0x72, 0x61, 0x64, 0x65, 0x4e, 0x6f, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x54, 0x72, 0x61, 0x64, 0x65, 0x4e, 0x6f, 0x12, 0x2a, 0x0a,
	0x07, 0x50, 0x61, 0x79, 0x54, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10,
	0x2e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x50, 0x61, 0x79, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x07, 0x50, 0x61, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x41, 0x6c, 0x69,
	0x70, 0x61, 0x79, 0x57, 0x61, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x41, 0x6c,
	0x69, 0x70, 0x61, 0x79, 0x57, 0x61, 0x70, 0x12, 0x35, 0x0a, 0x08, 0x57, 0x78, 0x55, 0x6e, 0x69,
	0x41, 0x70, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x61, 0x79, 0x6d,
	0x65, 0x6e, 0x74, 0x2e, 0x57, 0x78, 0x55, 0x6e, 0x69, 0x41, 0x70, 0x70, 0x50, 0x61, 0x79, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x52, 0x08, 0x57, 0x78, 0x55, 0x6e, 0x69, 0x41, 0x70, 0x70, 0x12, 0x35,
	0x0a, 0x08, 0x54, 0x69, 0x6b, 0x54, 0x6f, 0x6b, 0x45, 0x63, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x54, 0x69, 0x6b, 0x74, 0x6f,
	0x6b, 0x45, 0x63, 0x50, 0x61, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x08, 0x54, 0x69, 0x6b,
	0x54, 0x6f, 0x6b, 0x45, 0x63, 0x22, 0xd4, 0x01, 0x0a, 0x10, 0x57, 0x78, 0x55, 0x6e, 0x69, 0x41,
	0x70, 0x70, 0x50, 0x61, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65,
	0x53, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x54, 0x69, 0x6d,
	0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x53,
	0x74, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x53,
	0x74, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x53, 0x69, 0x67, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x53, 0x69, 0x67, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x53,
	0x69, 0x67, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x50, 0x61, 0x79, 0x53, 0x69,
	0x67, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x6e, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x6e, 0x22, 0x4c, 0x0a, 0x10,
	0x54, 0x69, 0x6b, 0x74, 0x6f, 0x6b, 0x45, 0x63, 0x50, 0x61, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x18, 0x0a, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x2a, 0x34, 0x0a, 0x07, 0x50, 0x61,
	0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0d, 0x0a, 0x09, 0x41, 0x6c, 0x69, 0x70, 0x61, 0x79, 0x57,
	0x61, 0x70, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x57, 0x78, 0x55, 0x6e, 0x69, 0x41, 0x70, 0x70,
	0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x54, 0x69, 0x6b, 0x74, 0x6f, 0x6b, 0x45, 0x63, 0x10, 0x02,
	0x32, 0x42, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x37, 0x0a, 0x08, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x50, 0x61, 0x79, 0x12, 0x14, 0x2e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e,
	0x74, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x50, 0x61, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e,
	0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x50, 0x61, 0x79,
	0x52, 0x65, 0x73, 0x70, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_payment_proto_rawDescOnce sync.Once
	file_payment_proto_rawDescData = file_payment_proto_rawDesc
)

func file_payment_proto_rawDescGZIP() []byte {
	file_payment_proto_rawDescOnce.Do(func() {
		file_payment_proto_rawDescData = protoimpl.X.CompressGZIP(file_payment_proto_rawDescData)
	})
	return file_payment_proto_rawDescData
}

var file_payment_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_payment_proto_goTypes = []interface{}{
	(PayType)(0),             // 0: payment.PayType
	(*OrderPayReq)(nil),      // 1: payment.OrderPayReq
	(*OrderPayResp)(nil),     // 2: payment.OrderPayResp
	(*WxUniAppPayReply)(nil), // 3: payment.WxUniAppPayReply
	(*TiktokEcPayReply)(nil), // 4: payment.TiktokEcPayReply
}
var file_payment_proto_depIdxs = []int32{
	0, // 0: payment.OrderPayReq.PayType:type_name -> payment.PayType
	0, // 1: payment.OrderPayResp.PayType:type_name -> payment.PayType
	3, // 2: payment.OrderPayResp.WxUniApp:type_name -> payment.WxUniAppPayReply
	4, // 3: payment.OrderPayResp.TikTokEc:type_name -> payment.TiktokEcPayReply
	1, // 4: payment.Payment.OrderPay:input_type -> payment.OrderPayReq
	2, // 5: payment.Payment.OrderPay:output_type -> payment.OrderPayResp
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_payment_proto_init() }
func file_payment_proto_init() {
	if File_payment_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_payment_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderPayReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payment_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderPayResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payment_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WxUniAppPayReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payment_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TiktokEcPayReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_payment_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_proto_goTypes,
		DependencyIndexes: file_payment_proto_depIdxs,
		EnumInfos:         file_payment_proto_enumTypes,
		MessageInfos:      file_payment_proto_msgTypes,
	}.Build()
	File_payment_proto = out.File
	file_payment_proto_rawDesc = nil
	file_payment_proto_goTypes = nil
	file_payment_proto_depIdxs = nil
}
