// Code generated by sql2gorm. DO NOT EDIT.
package model

import (
	"gitee.com/zhuyunkj/pay-gateway/comm/client"
	"gitee.com/zhuyunkj/pay-gateway/db"
	kv_m "gitee.com/zhuyunkj/zhuyun-core/kv_monitor"
	"github.com/jinzhu/gorm"
	"github.com/zeromicro/go-zero/core/logx"
	"time"
)

var (
	getPayConfigAlipayErr = kv_m.Register{kv_m.Regist(&kv_m.Monitor{kv_m.CounterValue, kv_m.KvLabels{"kind": "common"}, "getPayConfigAlipayErr", nil, "获取支付宝支付配置失败", nil})}
)

// 支付宝配置
type PmPayConfigAlipayTable struct {
	ID               int       `gorm:"column:id;primary_key;AUTO_INCREMENT" json:"id"`
	AppID            string    `gorm:"column:app_id;NOT NULL" json:"app_id"`                           // 应用id
	PrivateKey       string    `gorm:"column:private_key" json:"private_key"`                          // 私有key
	AppCertPublicKey string    `gorm:"column:app_cert_public_key;NOT NULL" json:"app_cert_public_key"` // 证书
	PublicKey        string    `gorm:"column:public_key;NOT NULL" json:"public_key"`                   // 证书
	PayRootCert      string    `gorm:"column:pay_root_cert;NOT NULL" json:"pay_root_cert"`             // 根证书
	IsProduction     int       `gorm:"column:is_production;default:0;NOT NULL" json:"is_production"`   // 是否生产 0否 1是
	Remark           string    `gorm:"column:remark;NOT NULL" json:"remark"`                           // 备注信息
	CreatedAt        time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt        time.Time `gorm:"column:updated_at" json:"updated_at"`
}

func (m *PmPayConfigAlipayTable) TableName() string {
	return "pm_pay_config_alipay"
}

func (m *PmPayConfigAlipayTable) TransClientConfig() (clientCfg *client.AliPayConfig) {
	clientCfg = &client.AliPayConfig{
		AppId:            m.AppID,
		PrivateKey:       m.PrivateKey,
		PublicKey:        m.PublicKey,
		AppCertPublicKey: m.AppCertPublicKey,
		PayRootCert:      m.PayRootCert,
	}
	if m.IsProduction == 1 {
		clientCfg.IsProduction = true
	}
	return
}

type PmPayConfigAlipayModel struct {
	DB *gorm.DB
}

func NewPmPayConfigAlipayModel(dbName string) *PmPayConfigAlipayModel {
	return &PmPayConfigAlipayModel{
		DB: db.WithDBContext(dbName),
	}
}

//获取应用配置信息
func (o *PmPayConfigAlipayModel) GetOneByAppID(appID string) (appConfig *PmPayConfigAlipayTable, err error) {
	var cfg PmPayConfigAlipayTable
	err = o.DB.Where(" `app_id` = ?", appID).First(&cfg).Error
	if err != nil {
		logx.Errorf("获取app配置信息失败，err:=%v,appID=%s", err, appID)
		getPayConfigAlipayErr.CounterInc()
		return nil, err
	}
	return &cfg, nil
}
