// Code generated by sql2gorm. DO NOT EDIT.
package model

import (
	"gitee.com/zhuyunkj/pay-gateway/common/client"
	"gitee.com/zhuyunkj/pay-gateway/db"
	kv_m "gitee.com/zhuyunkj/zhuyun-core/kv_monitor"
	"github.com/zeromicro/go-zero/core/logx"
	"gorm.io/gorm"
	"time"
)

var (
	getPayConfigTiktokErr = kv_m.Register{kv_m.Regist(&kv_m.Monitor{kv_m.CounterValue, kv_m.KvLabels{"kind": "common"}, "getPayConfigTiktokErr", nil, "获取抖音支付配置失败", nil})}
)

// 字节支付配置
type PmPayConfigTiktokTable struct {
	ID        int       `gorm:"column:id;primary_key;AUTO_INCREMENT" json:"id"`
	AppID     string    `gorm:"column:app_id;NOT NULL" json:"app_id"`         // 应用id
	Salt      string    `gorm:"column:salt;NOT NULL" json:"salt"`             // 加密参数
	NotifyUrl string    `gorm:"column:notify_url;NOT NULL" json:"notify_url"` // 回调地址
	Token     string    `gorm:"column:token;NOT NULL" json:"token"`           // token
	Remark    string    `gorm:"column:remark;NOT NULL" json:"remark"`         // 备注信息
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updated_at"`
}

func (m *PmPayConfigTiktokTable) TableName() string {
	return "pm_pay_config_tiktok"
}

func (m *PmPayConfigTiktokTable) TransClientConfig() (clientCfg *client.TikTokPayConfig) {
	clientCfg = &client.TikTokPayConfig{
		AppId:     m.AppID,
		SALT:      m.Salt,
		NotifyUrl: m.NotifyUrl,
		Token:     m.Token,
	}
	return
}

type PmPayConfigTiktokModel struct {
	DB *gorm.DB
}

func NewPmPayConfigTiktokModel(dbName string) *PmPayConfigTiktokModel {
	return &PmPayConfigTiktokModel{
		DB: db.WithDBContext(dbName),
	}
}

//获取应用配置信息
func (o *PmPayConfigTiktokModel) GetOneByAppID(appID string) (appConfig *PmPayConfigTiktokTable, err error) {
	var cfg PmPayConfigTiktokTable
	err = o.DB.Where(" `app_id` = ?", appID).First(&cfg).Error
	if err != nil {
		logx.Errorf("获取app配置信息失败，err:=%v,appID=%s", err, appID)
		getPayConfigTiktokErr.CounterInc()
		return nil, err
	}
	return &cfg, nil
}
