// Code generated by sql2gorm. DO NOT EDIT.
package model

import (
	"gitee.com/zhuyunkj/pay-gateway/db"
	redisdb "gitee.com/zhuyunkj/zhuyun-core/cache"
	"github.com/jinzhu/gorm"
	"time"
)

// 支付订单
type PmPayOrderTable struct {
	ID           uint      `gorm:"column:id;primary_key;AUTO_INCREMENT" json:"id"`
	OrderSn      string    `gorm:"column:order_sn;NOT NULL" json:"order_sn"`                     // 订单唯一标识
	AppPkgName   string    `gorm:"column:app_pkg_name;NOT NULL" json:"app_pkg_name"`             // 来源包名
	Amount       int       `gorm:"column:amount;default:0;NOT NULL" json:"amount"`               // 订单金额（分）
	NotifyAmount int       `gorm:"column:notify_amount;default:0;NOT NULL" json:"notify_amount"` // 回调金额（分）
	Subject      string    `gorm:"column:subject;NOT NULL" json:"subject"`                       // 订单标题
	PayType      int       `gorm:"column:pay_type;default:0;NOT NULL" json:"pay_type"`           // 支付方式
	NotifyUrl    string    `gorm:"column:notify_url;NOT NULL" json:"notify_url"`                 // 回调通知地址
	CreatedAt    time.Time `gorm:"column:created_at;type:datetime" json:"created_at"`
	UpdatedAt    time.Time `gorm:"column:updated_at;type:datetime" json:"updated_at"`
}

func (m *PmPayOrderTable) TableName() string {
	return "pm_pay_order"
}

type PmPayOrderModel struct {
	DB  *gorm.DB
	RDb *redisdb.RedisInstance
}

func NewPmPayOrderModel(dbName string) *PmPayOrderModel {
	return &PmPayOrderModel{
		DB:  db.WithDBContext(dbName),
		RDb: db.WithRedisDBContext(dbName),
	}
}
