// Code generated by sql2gorm. DO NOT EDIT.
package model

import (
	"errors"
	"fmt"
	"gitee.com/zhuyunkj/pay-gateway/db"
	kv_m "gitee.com/zhuyunkj/zhuyun-core/kv_monitor"
	"gitee.com/zhuyunkj/zhuyun-core/util"
	"github.com/zeromicro/go-zero/core/logx"
	"gorm.io/gorm"
	"time"
)

var (
	createPayOrderErr    = kv_m.Register{kv_m.Regist(&kv_m.Monitor{kv_m.CounterValue, kv_m.KvLabels{"kind": "common"}, "createPayOrderErr", nil, "创建支付订单失败", nil})}
	updateNofityOrderErr = kv_m.Register{kv_m.Regist(&kv_m.Monitor{kv_m.CounterValue, kv_m.KvLabels{"kind": "common"}, "updateNofityOrderErr", nil, "更新回调订单失败", nil})}
	getPayOrderErr       = kv_m.Register{kv_m.Regist(&kv_m.Monitor{kv_m.CounterValue, kv_m.KvLabels{"kind": "common"}, "getPayOrderErr", nil, "获取支付订单失败", nil})}
)

const (
	//支付状态
	PmPayOrderTablePayStatusNo   = 0
	PmPayOrderTablePayStatusPaid = 1
	//支付方式
	PmPayOrderTablePayTypeWechatPayUni = 1
	PmPayOrderTablePayTypeTiktokPayEc  = 2
)

// 支付订单
type PmPayOrderTable struct {
	ID           uint      `gorm:"column:id;primary_key;AUTO_INCREMENT" json:"id"`
	OrderSn      string    `gorm:"column:order_sn;NOT NULL" json:"order_sn"`                     // 订单唯一标识
	AppPkgName   string    `gorm:"column:app_pkg_name;NOT NULL" json:"app_pkg_name"`             // 来源包名
	Amount       int       `gorm:"column:amount;default:0;NOT NULL" json:"amount"`               // 订单金额（分）
	NotifyAmount int       `gorm:"column:notify_amount;default:0;NOT NULL" json:"notify_amount"` // 回调金额（分）
	Subject      string    `gorm:"column:subject;NOT NULL" json:"subject"`                       // 订单标题
	PayType      int       `gorm:"column:pay_type;default:0;NOT NULL" json:"pay_type"`           // 支付方式  1微信小程序支付 2头条小程序支付
	NotifyUrl    string    `gorm:"column:notify_url;NOT NULL" json:"notify_url"`                 // 回调通知地址
	PayStatus    int       `gorm:"column:pay_status;NOT NULL" json:"pay_status"`                 // 支付状态 0未支付  1已支付
	PayAppId     string    `gorm:"column:pay_app_id;NOT NULL" json:"pay_app_id"`                 //第三方支付的appid
	CreatedAt    time.Time `gorm:"column:created_at;type:datetime" json:"created_at"`
	UpdatedAt    time.Time `gorm:"column:updated_at;type:datetime" json:"updated_at"`
}

func (m *PmPayOrderTable) TableName() string {
	return "pm_pay_order"
}

type PmPayOrderModel struct {
	DB *gorm.DB
}

func NewPmPayOrderModel(dbName string) *PmPayOrderModel {
	return &PmPayOrderModel{
		DB: db.WithDBContext(dbName),
	}
}

//创建订单
func (o *PmPayOrderModel) Create(info *PmPayOrderTable) error {
	err := o.DB.Create(info).Error
	if err != nil {
		logx.Errorf("创建支付订单失败，err:=%v", err)
		createPayOrderErr.CounterInc()
	}
	return err
}

//获取订单信息
func (o *PmPayOrderModel) GetOneByCode(orderSn string) (info *PmPayOrderTable, err error) {
	var orderInfo PmPayOrderTable
	err = o.DB.Where("`order_sn` = ? ", orderSn).First(&orderInfo).Error
	if errors.Is(err, gorm.ErrRecordNotFound) {
		return nil, nil
	}
	if err != nil {
		logx.Errorf("获取订单信息失败，err:=%v,order_sn=%s", err, orderSn)
		getPayOrderErr.CounterInc()
		return nil, err
	}
	return &orderInfo, nil
}

func (o *PmPayOrderModel) UpdateNotify(info *PmPayOrderTable) error {
	err := o.DB.Save(&info).Error
	if err != nil {
		logx.Errorf("更新回调订单失败，err=%v", err)
		updateNofityOrderErr.CounterInc()
	}
	return err
}

func (o *PmPayOrderModel) UpdatePayAppID(orderSn string, payAppId string) (err error) {
	err = o.DB.Model(&PmPayOrderTable{}).Where("order_sn = ?", orderSn).Update("pay_app_id", payAppId).Error
	if err != nil {
		err = fmt.Errorf("UpdatePayAppID Err: %v", err)
		util.CheckError(err.Error())
	}
	return

}
