// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: payment.proto

package payment

import (
	"context"

	"gitlab.muchcloud.com/consumer-project/pay-gateway/rpc/pb/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AliRefundResp                 = pb.AliRefundResp
	AlipayAgreementModifyReq      = pb.AlipayAgreementModifyReq
	AlipayCheckAccountReq         = pb.AlipayCheckAccountReq
	AlipayCheckAccountResp        = pb.AlipayCheckAccountResp
	AlipayCommonResp              = pb.AlipayCommonResp
	AlipayFundTransUniTransferReq = pb.AlipayFundTransUniTransferReq
	AlipayPageSignReq             = pb.AlipayPageSignReq
	AlipayPageSignResp            = pb.AlipayPageSignResp
	AlipayPageUnSignReq           = pb.AlipayPageUnSignReq
	AlipayRefundReq               = pb.AlipayRefundReq
	AlipayTradePayReq             = pb.AlipayTradePayReq
	AlipayTradeReq                = pb.AlipayTradeReq
	AutoPkgAddReq                 = pb.AutoPkgAddReq
	AutoPkgAddResp                = pb.AutoPkgAddResp
	BindHuaweiPayDataReq          = pb.BindHuaweiPayDataReq
	BindHuaweiPayDataResp         = pb.BindHuaweiPayDataResp
	ClosePayOrderReq              = pb.ClosePayOrderReq
	CreateDouyinRefundReq         = pb.CreateDouyinRefundReq
	CreateDouyinRefundResp        = pb.CreateDouyinRefundResp
	CreateRefundResp              = pb.CreateRefundResp
	DouyinGeneralTradeReply       = pb.DouyinGeneralTradeReply
	DouyinGeneralTradeReq         = pb.DouyinGeneralTradeReq
	DouyinPeriodOrderReq          = pb.DouyinPeriodOrderReq
	DouyinPeriodOrderResp         = pb.DouyinPeriodOrderResp
	DyOrderRefundReq              = pb.DyOrderRefundReq
	DyOrderRefundResp             = pb.DyOrderRefundResp
	DyPeriodOrderReq              = pb.DyPeriodOrderReq
	DyPeriodOrderResp             = pb.DyPeriodOrderResp
	DySignedOrderInfo             = pb.DySignedOrderInfo
	Empty                         = pb.Empty
	KsUniAppReply                 = pb.KsUniAppReply
	OrderPayReq                   = pb.OrderPayReq
	OrderPayResp                  = pb.OrderPayResp
	OrderStatusReq                = pb.OrderStatusReq
	OrderStatusResp               = pb.OrderStatusResp
	PayeeInfo                     = pb.PayeeInfo
	Schema                        = pb.Schema
	TiktokEcPayReply              = pb.TiktokEcPayReply
	UnsubscribeHuaweiReq          = pb.UnsubscribeHuaweiReq
	UnsubscribeHuaweiResp         = pb.UnsubscribeHuaweiResp
	WechatMiniRefundQueryReq      = pb.WechatMiniRefundQueryReq
	WechatMiniRefundQueryResp     = pb.WechatMiniRefundQueryResp
	WechatMiniRefundReq           = pb.WechatMiniRefundReq
	WechatMiniRefundResp          = pb.WechatMiniRefundResp
	WechatMiniXPayQueryOrderReq   = pb.WechatMiniXPayQueryOrderReq
	WechatMiniXPayQueryOrderResp  = pb.WechatMiniXPayQueryOrderResp
	WechatMiniXPayRefundReq       = pb.WechatMiniXPayRefundReq
	WechatMiniXPayRefundResp      = pb.WechatMiniXPayRefundResp
	WechatRefundOrderReq          = pb.WechatRefundOrderReq
	WxH5PayReplay                 = pb.WxH5PayReplay
	WxNativePayReply              = pb.WxNativePayReply
	WxUniAppPayReply              = pb.WxUniAppPayReply
	WxUnifiedPayReply             = pb.WxUnifiedPayReply

	Payment interface {
		// 创建支付订单
		OrderPay(ctx context.Context, in *OrderPayReq, opts ...grpc.CallOption) (*OrderPayResp, error)
		// 关闭订单
		ClosePayOrder(ctx context.Context, in *ClosePayOrderReq, opts ...grpc.CallOption) (*Empty, error)
		// 支付宝转出
		AlipayFundTransUniTransfer(ctx context.Context, in *AlipayFundTransUniTransferReq, opts ...grpc.CallOption) (*Empty, error)
		// 查询订单
		OrderStatus(ctx context.Context, in *OrderStatusReq, opts ...grpc.CallOption) (*OrderStatusResp, error)
		// 支付宝转出账号校验
		AlipayCheckAccount(ctx context.Context, in *AlipayCheckAccountReq, opts ...grpc.CallOption) (*AlipayCheckAccountResp, error)
		// 抖音退款订单
		DyOrderRefund(ctx context.Context, in *DyOrderRefundReq, opts ...grpc.CallOption) (*DyOrderRefundResp, error)
		// 抖音退款 使用通用交易系统
		CreateDouyinRefund(ctx context.Context, in *CreateDouyinRefundReq, opts ...grpc.CallOption) (*CreateDouyinRefundResp, error)
		// 支付宝：创建支付
		AlipayTrade(ctx context.Context, in *AlipayTradeReq, opts ...grpc.CallOption) (*AlipayPageSignResp, error)
		// 支付宝：支付并签约
		AlipayPagePayAndSign(ctx context.Context, in *AlipayPageSignReq, opts ...grpc.CallOption) (*AlipayPageSignResp, error)
		// 支付宝h5支付
		AlipayH5Pay(ctx context.Context, in *AlipayPageSignReq, opts ...grpc.CallOption) (*AlipayPageSignResp, error)
		// 支付宝新的充值订阅 可以选择不同的支付宝账号：支付并签约
		AlipayPagePayAndSignChoiceAccount(ctx context.Context, in *AlipayPageSignReq, opts ...grpc.CallOption) (*AlipayPageSignResp, error)
		// 支付宝：解约
		AlipayPageUnSign(ctx context.Context, in *AlipayPageUnSignReq, opts ...grpc.CallOption) (*AlipayCommonResp, error)
		// 支付宝：创建退款订单
		AlipayCreateRefund(ctx context.Context, in *AlipayRefundReq, opts ...grpc.CallOption) (*CreateRefundResp, error)
		// 支付宝：退款
		AlipayRefund(ctx context.Context, in *AlipayRefundReq, opts ...grpc.CallOption) (*AliRefundResp, error)
		// 支付宝：订阅扣款
		AlipayTradePay(ctx context.Context, in *AlipayTradePayReq, opts ...grpc.CallOption) (*AlipayCommonResp, error)
		// 支付宝：签约延期
		AlipayAgreementModify(ctx context.Context, in *AlipayAgreementModifyReq, opts ...grpc.CallOption) (*AlipayCommonResp, error)
		// 微信统一下单接口，JSAPI，对接文档：https://pay.weixin.qq.com/docs/merchant/products/jsapi-payment/introduction.html
		WechatUnifiedOrder(ctx context.Context, in *AlipayPageSignReq, opts ...grpc.CallOption) (*WxUnifiedPayReply, error)
		// 微信统一支付退款
		WechatRefundOrder(ctx context.Context, in *WechatRefundOrderReq, opts ...grpc.CallOption) (*CreateRefundResp, error)
		// 微信h5支付，对接文档：https://pay.weixin.qq.com/docs/merchant/apis/h5-payment/direct-jsons/h5-prepay.html
		WechatPayH5Order(ctx context.Context, in *AlipayPageSignReq, opts ...grpc.CallOption) (*WxH5PayReplay, error)
		// 绑定订单号和华为购买token
		BindHuaweiPayData(ctx context.Context, in *BindHuaweiPayDataReq, opts ...grpc.CallOption) (*BindHuaweiPayDataResp, error)
		// 用户主动解除华为订阅
		UnsubscribeHuawei(ctx context.Context, in *UnsubscribeHuaweiReq, opts ...grpc.CallOption) (*UnsubscribeHuaweiResp, error)
		// 用户主动解除华为订阅后的退款操作
		UnsubscribeHuaweiRefund(ctx context.Context, in *UnsubscribeHuaweiReq, opts ...grpc.CallOption) (*UnsubscribeHuaweiResp, error)
		// 抖音周期代扣相关查询和修改(包括解约)
		DouyinPeriodOrder(ctx context.Context, in *DouyinPeriodOrderReq, opts ...grpc.CallOption) (*DouyinPeriodOrderResp, error)
		// 小程序-微信的退款申请
		WechatMiniRefund(ctx context.Context, in *WechatMiniRefundReq, opts ...grpc.CallOption) (*WechatMiniRefundResp, error)
		// 小程序-微信的退款单详情
		WechatMiniRefundQuery(ctx context.Context, in *WechatMiniRefundQueryReq, opts ...grpc.CallOption) (*WechatMiniRefundQueryResp, error)
		// 微信虚拟支付-退款申请
		WechatMiniXPayRefund(ctx context.Context, in *WechatMiniXPayRefundReq, opts ...grpc.CallOption) (*WechatMiniXPayRefundResp, error)
		// 微信虚拟支付-退款/订单详情
		WechatMiniXPayQueryOrder(ctx context.Context, in *WechatMiniXPayQueryOrderReq, opts ...grpc.CallOption) (*WechatMiniXPayQueryOrderResp, error)
		// AutoPkgAdd 自动创建应用
		AutoPkgAdd(ctx context.Context, in *AutoPkgAddReq, opts ...grpc.CallOption) (*AutoPkgAddResp, error)
		// DyPeriodOrder 查询抖音周期代扣订单
		DyPeriodOrder(ctx context.Context, in *DyPeriodOrderReq, opts ...grpc.CallOption) (*DyPeriodOrderResp, error)
	}

	defaultPayment struct {
		cli zrpc.Client
	}
)

func NewPayment(cli zrpc.Client) Payment {
	return &defaultPayment{
		cli: cli,
	}
}

// 创建支付订单
func (m *defaultPayment) OrderPay(ctx context.Context, in *OrderPayReq, opts ...grpc.CallOption) (*OrderPayResp, error) {
	client := pb.NewPaymentClient(m.cli.Conn())
	return client.OrderPay(ctx, in, opts...)
}

// 关闭订单
func (m *defaultPayment) ClosePayOrder(ctx context.Context, in *ClosePayOrderReq, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewPaymentClient(m.cli.Conn())
	return client.ClosePayOrder(ctx, in, opts...)
}

// 支付宝转出
func (m *defaultPayment) AlipayFundTransUniTransfer(ctx context.Context, in *AlipayFundTransUniTransferReq, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewPaymentClient(m.cli.Conn())
	return client.AlipayFundTransUniTransfer(ctx, in, opts...)
}

// 查询订单
func (m *defaultPayment) OrderStatus(ctx context.Context, in *OrderStatusReq, opts ...grpc.CallOption) (*OrderStatusResp, error) {
	client := pb.NewPaymentClient(m.cli.Conn())
	return client.OrderStatus(ctx, in, opts...)
}

// 支付宝转出账号校验
func (m *defaultPayment) AlipayCheckAccount(ctx context.Context, in *AlipayCheckAccountReq, opts ...grpc.CallOption) (*AlipayCheckAccountResp, error) {
	client := pb.NewPaymentClient(m.cli.Conn())
	return client.AlipayCheckAccount(ctx, in, opts...)
}

// 抖音退款订单
func (m *defaultPayment) DyOrderRefund(ctx context.Context, in *DyOrderRefundReq, opts ...grpc.CallOption) (*DyOrderRefundResp, error) {
	client := pb.NewPaymentClient(m.cli.Conn())
	return client.DyOrderRefund(ctx, in, opts...)
}

// 抖音退款 使用通用交易系统
func (m *defaultPayment) CreateDouyinRefund(ctx context.Context, in *CreateDouyinRefundReq, opts ...grpc.CallOption) (*CreateDouyinRefundResp, error) {
	client := pb.NewPaymentClient(m.cli.Conn())
	return client.CreateDouyinRefund(ctx, in, opts...)
}

// 支付宝：创建支付
func (m *defaultPayment) AlipayTrade(ctx context.Context, in *AlipayTradeReq, opts ...grpc.CallOption) (*AlipayPageSignResp, error) {
	client := pb.NewPaymentClient(m.cli.Conn())
	return client.AlipayTrade(ctx, in, opts...)
}

// 支付宝：支付并签约
func (m *defaultPayment) AlipayPagePayAndSign(ctx context.Context, in *AlipayPageSignReq, opts ...grpc.CallOption) (*AlipayPageSignResp, error) {
	client := pb.NewPaymentClient(m.cli.Conn())
	return client.AlipayPagePayAndSign(ctx, in, opts...)
}

// 支付宝h5支付
func (m *defaultPayment) AlipayH5Pay(ctx context.Context, in *AlipayPageSignReq, opts ...grpc.CallOption) (*AlipayPageSignResp, error) {
	client := pb.NewPaymentClient(m.cli.Conn())
	return client.AlipayH5Pay(ctx, in, opts...)
}

// 支付宝新的充值订阅 可以选择不同的支付宝账号：支付并签约
func (m *defaultPayment) AlipayPagePayAndSignChoiceAccount(ctx context.Context, in *AlipayPageSignReq, opts ...grpc.CallOption) (*AlipayPageSignResp, error) {
	client := pb.NewPaymentClient(m.cli.Conn())
	return client.AlipayPagePayAndSignChoiceAccount(ctx, in, opts...)
}

// 支付宝：解约
func (m *defaultPayment) AlipayPageUnSign(ctx context.Context, in *AlipayPageUnSignReq, opts ...grpc.CallOption) (*AlipayCommonResp, error) {
	client := pb.NewPaymentClient(m.cli.Conn())
	return client.AlipayPageUnSign(ctx, in, opts...)
}

// 支付宝：创建退款订单
func (m *defaultPayment) AlipayCreateRefund(ctx context.Context, in *AlipayRefundReq, opts ...grpc.CallOption) (*CreateRefundResp, error) {
	client := pb.NewPaymentClient(m.cli.Conn())
	return client.AlipayCreateRefund(ctx, in, opts...)
}

// 支付宝：退款
func (m *defaultPayment) AlipayRefund(ctx context.Context, in *AlipayRefundReq, opts ...grpc.CallOption) (*AliRefundResp, error) {
	client := pb.NewPaymentClient(m.cli.Conn())
	return client.AlipayRefund(ctx, in, opts...)
}

// 支付宝：订阅扣款
func (m *defaultPayment) AlipayTradePay(ctx context.Context, in *AlipayTradePayReq, opts ...grpc.CallOption) (*AlipayCommonResp, error) {
	client := pb.NewPaymentClient(m.cli.Conn())
	return client.AlipayTradePay(ctx, in, opts...)
}

// 支付宝：签约延期
func (m *defaultPayment) AlipayAgreementModify(ctx context.Context, in *AlipayAgreementModifyReq, opts ...grpc.CallOption) (*AlipayCommonResp, error) {
	client := pb.NewPaymentClient(m.cli.Conn())
	return client.AlipayAgreementModify(ctx, in, opts...)
}

// 微信统一下单接口，JSAPI，对接文档：https://pay.weixin.qq.com/docs/merchant/products/jsapi-payment/introduction.html
func (m *defaultPayment) WechatUnifiedOrder(ctx context.Context, in *AlipayPageSignReq, opts ...grpc.CallOption) (*WxUnifiedPayReply, error) {
	client := pb.NewPaymentClient(m.cli.Conn())
	return client.WechatUnifiedOrder(ctx, in, opts...)
}

// 微信统一支付退款
func (m *defaultPayment) WechatRefundOrder(ctx context.Context, in *WechatRefundOrderReq, opts ...grpc.CallOption) (*CreateRefundResp, error) {
	client := pb.NewPaymentClient(m.cli.Conn())
	return client.WechatRefundOrder(ctx, in, opts...)
}

// 微信h5支付，对接文档：https://pay.weixin.qq.com/docs/merchant/apis/h5-payment/direct-jsons/h5-prepay.html
func (m *defaultPayment) WechatPayH5Order(ctx context.Context, in *AlipayPageSignReq, opts ...grpc.CallOption) (*WxH5PayReplay, error) {
	client := pb.NewPaymentClient(m.cli.Conn())
	return client.WechatPayH5Order(ctx, in, opts...)
}

// 绑定订单号和华为购买token
func (m *defaultPayment) BindHuaweiPayData(ctx context.Context, in *BindHuaweiPayDataReq, opts ...grpc.CallOption) (*BindHuaweiPayDataResp, error) {
	client := pb.NewPaymentClient(m.cli.Conn())
	return client.BindHuaweiPayData(ctx, in, opts...)
}

// 用户主动解除华为订阅
func (m *defaultPayment) UnsubscribeHuawei(ctx context.Context, in *UnsubscribeHuaweiReq, opts ...grpc.CallOption) (*UnsubscribeHuaweiResp, error) {
	client := pb.NewPaymentClient(m.cli.Conn())
	return client.UnsubscribeHuawei(ctx, in, opts...)
}

// 用户主动解除华为订阅后的退款操作
func (m *defaultPayment) UnsubscribeHuaweiRefund(ctx context.Context, in *UnsubscribeHuaweiReq, opts ...grpc.CallOption) (*UnsubscribeHuaweiResp, error) {
	client := pb.NewPaymentClient(m.cli.Conn())
	return client.UnsubscribeHuaweiRefund(ctx, in, opts...)
}

// 抖音周期代扣相关查询和修改(包括解约)
func (m *defaultPayment) DouyinPeriodOrder(ctx context.Context, in *DouyinPeriodOrderReq, opts ...grpc.CallOption) (*DouyinPeriodOrderResp, error) {
	client := pb.NewPaymentClient(m.cli.Conn())
	return client.DouyinPeriodOrder(ctx, in, opts...)
}

// 小程序-微信的退款申请
func (m *defaultPayment) WechatMiniRefund(ctx context.Context, in *WechatMiniRefundReq, opts ...grpc.CallOption) (*WechatMiniRefundResp, error) {
	client := pb.NewPaymentClient(m.cli.Conn())
	return client.WechatMiniRefund(ctx, in, opts...)
}

// 小程序-微信的退款单详情
func (m *defaultPayment) WechatMiniRefundQuery(ctx context.Context, in *WechatMiniRefundQueryReq, opts ...grpc.CallOption) (*WechatMiniRefundQueryResp, error) {
	client := pb.NewPaymentClient(m.cli.Conn())
	return client.WechatMiniRefundQuery(ctx, in, opts...)
}

// 微信虚拟支付-退款申请
func (m *defaultPayment) WechatMiniXPayRefund(ctx context.Context, in *WechatMiniXPayRefundReq, opts ...grpc.CallOption) (*WechatMiniXPayRefundResp, error) {
	client := pb.NewPaymentClient(m.cli.Conn())
	return client.WechatMiniXPayRefund(ctx, in, opts...)
}

// 微信虚拟支付-退款/订单详情
func (m *defaultPayment) WechatMiniXPayQueryOrder(ctx context.Context, in *WechatMiniXPayQueryOrderReq, opts ...grpc.CallOption) (*WechatMiniXPayQueryOrderResp, error) {
	client := pb.NewPaymentClient(m.cli.Conn())
	return client.WechatMiniXPayQueryOrder(ctx, in, opts...)
}

// AutoPkgAdd 自动创建应用
func (m *defaultPayment) AutoPkgAdd(ctx context.Context, in *AutoPkgAddReq, opts ...grpc.CallOption) (*AutoPkgAddResp, error) {
	client := pb.NewPaymentClient(m.cli.Conn())
	return client.AutoPkgAdd(ctx, in, opts...)
}

// DyPeriodOrder 查询抖音周期代扣订单
func (m *defaultPayment) DyPeriodOrder(ctx context.Context, in *DyPeriodOrderReq, opts ...grpc.CallOption) (*DyPeriodOrderResp, error) {
	client := pb.NewPaymentClient(m.cli.Conn())
	return client.DyPeriodOrder(ctx, in, opts...)
}
