// Code generated by goctl. DO NOT EDIT!
// Source: payment.proto

package payment

import (
	"context"

	"gitee.com/zhuyunkj/pay-gateway/rpc/pb/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ClosePayOrderReq = pb.ClosePayOrderReq
	Empty            = pb.Empty
	OrderPayReq      = pb.OrderPayReq
	OrderPayResp     = pb.OrderPayResp
	TiktokEcPayReply = pb.TiktokEcPayReply
	WxUniAppPayReply = pb.WxUniAppPayReply

	Payment interface {
		// 创建支付订单
		OrderPay(ctx context.Context, in *OrderPayReq, opts ...grpc.CallOption) (*OrderPayResp, error)
		// 关闭订单
		ClosePayOrder(ctx context.Context, in *ClosePayOrderReq, opts ...grpc.CallOption) (*Empty, error)
	}

	defaultPayment struct {
		cli zrpc.Client
	}
)

func NewPayment(cli zrpc.Client) Payment {
	return &defaultPayment{
		cli: cli,
	}
}

// 创建支付订单
func (m *defaultPayment) OrderPay(ctx context.Context, in *OrderPayReq, opts ...grpc.CallOption) (*OrderPayResp, error) {
	client := pb.NewPaymentClient(m.cli.Conn())
	return client.OrderPay(ctx, in, opts...)
}

// 关闭订单
func (m *defaultPayment) ClosePayOrder(ctx context.Context, in *ClosePayOrderReq, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewPaymentClient(m.cli.Conn())
	return client.ClosePayOrder(ctx, in, opts...)
}
