// Code generated by goctl. DO NOT EDIT!
// Source: payment.proto

package payment

import (
	"context"

	"gitee.com/zhuyunkj/pay-gateway/rpc/pb/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AlipayCheckAccountReq         = pb.AlipayCheckAccountReq
	AlipayCheckAccountResp        = pb.AlipayCheckAccountResp
	AlipayFundTransUniTransferReq = pb.AlipayFundTransUniTransferReq
	ClosePayOrderReq              = pb.ClosePayOrderReq
	Empty                         = pb.Empty
	OrderPayReq                   = pb.OrderPayReq
	OrderPayResp                  = pb.OrderPayResp
	OrderStatusReq                = pb.OrderStatusReq
	OrderStatusResp               = pb.OrderStatusResp
	PayeeInfo                     = pb.PayeeInfo
	TiktokEcPayReply              = pb.TiktokEcPayReply
	WxNativePayReply              = pb.WxNativePayReply
	WxUniAppPayReply              = pb.WxUniAppPayReply

	Payment interface {
		// 创建支付订单
		OrderPay(ctx context.Context, in *OrderPayReq, opts ...grpc.CallOption) (*OrderPayResp, error)
		// 关闭订单
		ClosePayOrder(ctx context.Context, in *ClosePayOrderReq, opts ...grpc.CallOption) (*Empty, error)
		// 支付宝转出
		AlipayFundTransUniTransfer(ctx context.Context, in *AlipayFundTransUniTransferReq, opts ...grpc.CallOption) (*Empty, error)
		// 查询订单
		OrderStatus(ctx context.Context, in *OrderStatusReq, opts ...grpc.CallOption) (*OrderStatusResp, error)
		// 支付宝转出账号校验
		AlipayCheckAccount(ctx context.Context, in *AlipayCheckAccountReq, opts ...grpc.CallOption) (*AlipayCheckAccountResp, error)
	}

	defaultPayment struct {
		cli zrpc.Client
	}
)

func NewPayment(cli zrpc.Client) Payment {
	return &defaultPayment{
		cli: cli,
	}
}

// 创建支付订单
func (m *defaultPayment) OrderPay(ctx context.Context, in *OrderPayReq, opts ...grpc.CallOption) (*OrderPayResp, error) {
	client := pb.NewPaymentClient(m.cli.Conn())
	return client.OrderPay(ctx, in, opts...)
}

// 关闭订单
func (m *defaultPayment) ClosePayOrder(ctx context.Context, in *ClosePayOrderReq, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewPaymentClient(m.cli.Conn())
	return client.ClosePayOrder(ctx, in, opts...)
}

// 支付宝转出
func (m *defaultPayment) AlipayFundTransUniTransfer(ctx context.Context, in *AlipayFundTransUniTransferReq, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewPaymentClient(m.cli.Conn())
	return client.AlipayFundTransUniTransfer(ctx, in, opts...)
}

// 查询订单
func (m *defaultPayment) OrderStatus(ctx context.Context, in *OrderStatusReq, opts ...grpc.CallOption) (*OrderStatusResp, error) {
	client := pb.NewPaymentClient(m.cli.Conn())
	return client.OrderStatus(ctx, in, opts...)
}

// 支付宝转出账号校验
func (m *defaultPayment) AlipayCheckAccount(ctx context.Context, in *AlipayCheckAccountReq, opts ...grpc.CallOption) (*AlipayCheckAccountResp, error) {
	client := pb.NewPaymentClient(m.cli.Conn())
	return client.AlipayCheckAccount(ctx, in, opts...)
}
