// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: payment.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Payment_OrderPay_FullMethodName                   = "/payment.Payment/OrderPay"
	Payment_ClosePayOrder_FullMethodName              = "/payment.Payment/ClosePayOrder"
	Payment_AlipayFundTransUniTransfer_FullMethodName = "/payment.Payment/AlipayFundTransUniTransfer"
	Payment_OrderStatus_FullMethodName                = "/payment.Payment/OrderStatus"
	Payment_AlipayCheckAccount_FullMethodName         = "/payment.Payment/AlipayCheckAccount"
	Payment_DyOrderRefund_FullMethodName              = "/payment.Payment/DyOrderRefund"
	Payment_AlipayTrade_FullMethodName                = "/payment.Payment/AlipayTrade"
	Payment_AlipayPagePayAndSign_FullMethodName       = "/payment.Payment/AlipayPagePayAndSign"
	Payment_AlipayPageUnSign_FullMethodName           = "/payment.Payment/AlipayPageUnSign"
	Payment_AlipayCreateRefund_FullMethodName         = "/payment.Payment/AlipayCreateRefund"
	Payment_AlipayRefund_FullMethodName               = "/payment.Payment/AlipayRefund"
	Payment_AlipayTradePay_FullMethodName             = "/payment.Payment/AlipayTradePay"
	Payment_AlipayAgreementModify_FullMethodName      = "/payment.Payment/AlipayAgreementModify"
	Payment_WechatUnifiedOrder_FullMethodName         = "/payment.Payment/WechatUnifiedOrder"
	Payment_WechatRefundOrder_FullMethodName          = "/payment.Payment/WechatRefundOrder"
	Payment_WechatPayH5Order_FullMethodName           = "/payment.Payment/WechatPayH5Order"
)

// PaymentClient is the client API for Payment service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaymentClient interface {
	// 创建支付订单
	OrderPay(ctx context.Context, in *OrderPayReq, opts ...grpc.CallOption) (*OrderPayResp, error)
	// 关闭订单
	ClosePayOrder(ctx context.Context, in *ClosePayOrderReq, opts ...grpc.CallOption) (*Empty, error)
	// 支付宝转出
	AlipayFundTransUniTransfer(ctx context.Context, in *AlipayFundTransUniTransferReq, opts ...grpc.CallOption) (*Empty, error)
	// 查询订单
	OrderStatus(ctx context.Context, in *OrderStatusReq, opts ...grpc.CallOption) (*OrderStatusResp, error)
	// 支付宝转出账号校验
	AlipayCheckAccount(ctx context.Context, in *AlipayCheckAccountReq, opts ...grpc.CallOption) (*AlipayCheckAccountResp, error)
	// 抖音退款订单
	DyOrderRefund(ctx context.Context, in *DyOrderRefundReq, opts ...grpc.CallOption) (*DyOrderRefundResp, error)
	// 支付宝：创建支付
	AlipayTrade(ctx context.Context, in *AlipayTradeReq, opts ...grpc.CallOption) (*AlipayPageSignResp, error)
	// 支付宝：支付并签约
	AlipayPagePayAndSign(ctx context.Context, in *AlipayPageSignReq, opts ...grpc.CallOption) (*AlipayPageSignResp, error)
	// 支付宝：解约
	AlipayPageUnSign(ctx context.Context, in *AlipayPageUnSignReq, opts ...grpc.CallOption) (*AlipayCommonResp, error)
	// 支付宝：创建退款订单
	AlipayCreateRefund(ctx context.Context, in *AlipayRefundReq, opts ...grpc.CallOption) (*CreateRefundResp, error)
	// 支付宝：退款
	AlipayRefund(ctx context.Context, in *AlipayRefundReq, opts ...grpc.CallOption) (*AliRefundResp, error)
	// 支付宝：订阅扣款
	AlipayTradePay(ctx context.Context, in *AlipayTradePayReq, opts ...grpc.CallOption) (*AlipayCommonResp, error)
	// 支付宝：签约延期
	AlipayAgreementModify(ctx context.Context, in *AlipayAgreementModifyReq, opts ...grpc.CallOption) (*AlipayCommonResp, error)
	// 微信统一下单接口，JSAPI，对接文档：https://pay.weixin.qq.com/docs/merchant/products/jsapi-payment/introduction.html
	WechatUnifiedOrder(ctx context.Context, in *AlipayPageSignReq, opts ...grpc.CallOption) (*WxUnifiedPayReply, error)
	// 微信统一支付退款
	WechatRefundOrder(ctx context.Context, in *WechatRefundOrderReq, opts ...grpc.CallOption) (*CreateRefundResp, error)
	// 微信h5支付，对接文档：https://pay.weixin.qq.com/docs/merchant/apis/h5-payment/direct-jsons/h5-prepay.html
	WechatPayH5Order(ctx context.Context, in *AlipayPageSignReq, opts ...grpc.CallOption) (*WxH5PayReplay, error)
}

type paymentClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentClient(cc grpc.ClientConnInterface) PaymentClient {
	return &paymentClient{cc}
}

func (c *paymentClient) OrderPay(ctx context.Context, in *OrderPayReq, opts ...grpc.CallOption) (*OrderPayResp, error) {
	out := new(OrderPayResp)
	err := c.cc.Invoke(ctx, Payment_OrderPay_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentClient) ClosePayOrder(ctx context.Context, in *ClosePayOrderReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, Payment_ClosePayOrder_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentClient) AlipayFundTransUniTransfer(ctx context.Context, in *AlipayFundTransUniTransferReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, Payment_AlipayFundTransUniTransfer_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentClient) OrderStatus(ctx context.Context, in *OrderStatusReq, opts ...grpc.CallOption) (*OrderStatusResp, error) {
	out := new(OrderStatusResp)
	err := c.cc.Invoke(ctx, Payment_OrderStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentClient) AlipayCheckAccount(ctx context.Context, in *AlipayCheckAccountReq, opts ...grpc.CallOption) (*AlipayCheckAccountResp, error) {
	out := new(AlipayCheckAccountResp)
	err := c.cc.Invoke(ctx, Payment_AlipayCheckAccount_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentClient) DyOrderRefund(ctx context.Context, in *DyOrderRefundReq, opts ...grpc.CallOption) (*DyOrderRefundResp, error) {
	out := new(DyOrderRefundResp)
	err := c.cc.Invoke(ctx, Payment_DyOrderRefund_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentClient) AlipayTrade(ctx context.Context, in *AlipayTradeReq, opts ...grpc.CallOption) (*AlipayPageSignResp, error) {
	out := new(AlipayPageSignResp)
	err := c.cc.Invoke(ctx, Payment_AlipayTrade_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentClient) AlipayPagePayAndSign(ctx context.Context, in *AlipayPageSignReq, opts ...grpc.CallOption) (*AlipayPageSignResp, error) {
	out := new(AlipayPageSignResp)
	err := c.cc.Invoke(ctx, Payment_AlipayPagePayAndSign_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentClient) AlipayPageUnSign(ctx context.Context, in *AlipayPageUnSignReq, opts ...grpc.CallOption) (*AlipayCommonResp, error) {
	out := new(AlipayCommonResp)
	err := c.cc.Invoke(ctx, Payment_AlipayPageUnSign_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentClient) AlipayCreateRefund(ctx context.Context, in *AlipayRefundReq, opts ...grpc.CallOption) (*CreateRefundResp, error) {
	out := new(CreateRefundResp)
	err := c.cc.Invoke(ctx, Payment_AlipayCreateRefund_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentClient) AlipayRefund(ctx context.Context, in *AlipayRefundReq, opts ...grpc.CallOption) (*AliRefundResp, error) {
	out := new(AliRefundResp)
	err := c.cc.Invoke(ctx, Payment_AlipayRefund_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentClient) AlipayTradePay(ctx context.Context, in *AlipayTradePayReq, opts ...grpc.CallOption) (*AlipayCommonResp, error) {
	out := new(AlipayCommonResp)
	err := c.cc.Invoke(ctx, Payment_AlipayTradePay_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentClient) AlipayAgreementModify(ctx context.Context, in *AlipayAgreementModifyReq, opts ...grpc.CallOption) (*AlipayCommonResp, error) {
	out := new(AlipayCommonResp)
	err := c.cc.Invoke(ctx, Payment_AlipayAgreementModify_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentClient) WechatUnifiedOrder(ctx context.Context, in *AlipayPageSignReq, opts ...grpc.CallOption) (*WxUnifiedPayReply, error) {
	out := new(WxUnifiedPayReply)
	err := c.cc.Invoke(ctx, Payment_WechatUnifiedOrder_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentClient) WechatRefundOrder(ctx context.Context, in *WechatRefundOrderReq, opts ...grpc.CallOption) (*CreateRefundResp, error) {
	out := new(CreateRefundResp)
	err := c.cc.Invoke(ctx, Payment_WechatRefundOrder_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentClient) WechatPayH5Order(ctx context.Context, in *AlipayPageSignReq, opts ...grpc.CallOption) (*WxH5PayReplay, error) {
	out := new(WxH5PayReplay)
	err := c.cc.Invoke(ctx, Payment_WechatPayH5Order_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentServer is the server API for Payment service.
// All implementations must embed UnimplementedPaymentServer
// for forward compatibility
type PaymentServer interface {
	// 创建支付订单
	OrderPay(context.Context, *OrderPayReq) (*OrderPayResp, error)
	// 关闭订单
	ClosePayOrder(context.Context, *ClosePayOrderReq) (*Empty, error)
	// 支付宝转出
	AlipayFundTransUniTransfer(context.Context, *AlipayFundTransUniTransferReq) (*Empty, error)
	// 查询订单
	OrderStatus(context.Context, *OrderStatusReq) (*OrderStatusResp, error)
	// 支付宝转出账号校验
	AlipayCheckAccount(context.Context, *AlipayCheckAccountReq) (*AlipayCheckAccountResp, error)
	// 抖音退款订单
	DyOrderRefund(context.Context, *DyOrderRefundReq) (*DyOrderRefundResp, error)
	// 支付宝：创建支付
	AlipayTrade(context.Context, *AlipayTradeReq) (*AlipayPageSignResp, error)
	// 支付宝：支付并签约
	AlipayPagePayAndSign(context.Context, *AlipayPageSignReq) (*AlipayPageSignResp, error)
	// 支付宝：解约
	AlipayPageUnSign(context.Context, *AlipayPageUnSignReq) (*AlipayCommonResp, error)
	// 支付宝：创建退款订单
	AlipayCreateRefund(context.Context, *AlipayRefundReq) (*CreateRefundResp, error)
	// 支付宝：退款
	AlipayRefund(context.Context, *AlipayRefundReq) (*AliRefundResp, error)
	// 支付宝：订阅扣款
	AlipayTradePay(context.Context, *AlipayTradePayReq) (*AlipayCommonResp, error)
	// 支付宝：签约延期
	AlipayAgreementModify(context.Context, *AlipayAgreementModifyReq) (*AlipayCommonResp, error)
	// 微信统一下单接口，JSAPI，对接文档：https://pay.weixin.qq.com/docs/merchant/products/jsapi-payment/introduction.html
	WechatUnifiedOrder(context.Context, *AlipayPageSignReq) (*WxUnifiedPayReply, error)
	// 微信统一支付退款
	WechatRefundOrder(context.Context, *WechatRefundOrderReq) (*CreateRefundResp, error)
	// 微信h5支付，对接文档：https://pay.weixin.qq.com/docs/merchant/apis/h5-payment/direct-jsons/h5-prepay.html
	WechatPayH5Order(context.Context, *AlipayPageSignReq) (*WxH5PayReplay, error)
	mustEmbedUnimplementedPaymentServer()
}

// UnimplementedPaymentServer must be embedded to have forward compatible implementations.
type UnimplementedPaymentServer struct {
}

func (UnimplementedPaymentServer) OrderPay(context.Context, *OrderPayReq) (*OrderPayResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OrderPay not implemented")
}
func (UnimplementedPaymentServer) ClosePayOrder(context.Context, *ClosePayOrderReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClosePayOrder not implemented")
}
func (UnimplementedPaymentServer) AlipayFundTransUniTransfer(context.Context, *AlipayFundTransUniTransferReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AlipayFundTransUniTransfer not implemented")
}
func (UnimplementedPaymentServer) OrderStatus(context.Context, *OrderStatusReq) (*OrderStatusResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OrderStatus not implemented")
}
func (UnimplementedPaymentServer) AlipayCheckAccount(context.Context, *AlipayCheckAccountReq) (*AlipayCheckAccountResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AlipayCheckAccount not implemented")
}
func (UnimplementedPaymentServer) DyOrderRefund(context.Context, *DyOrderRefundReq) (*DyOrderRefundResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DyOrderRefund not implemented")
}
func (UnimplementedPaymentServer) AlipayTrade(context.Context, *AlipayTradeReq) (*AlipayPageSignResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AlipayTrade not implemented")
}
func (UnimplementedPaymentServer) AlipayPagePayAndSign(context.Context, *AlipayPageSignReq) (*AlipayPageSignResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AlipayPagePayAndSign not implemented")
}
func (UnimplementedPaymentServer) AlipayPageUnSign(context.Context, *AlipayPageUnSignReq) (*AlipayCommonResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AlipayPageUnSign not implemented")
}
func (UnimplementedPaymentServer) AlipayCreateRefund(context.Context, *AlipayRefundReq) (*CreateRefundResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AlipayCreateRefund not implemented")
}
func (UnimplementedPaymentServer) AlipayRefund(context.Context, *AlipayRefundReq) (*AliRefundResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AlipayRefund not implemented")
}
func (UnimplementedPaymentServer) AlipayTradePay(context.Context, *AlipayTradePayReq) (*AlipayCommonResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AlipayTradePay not implemented")
}
func (UnimplementedPaymentServer) AlipayAgreementModify(context.Context, *AlipayAgreementModifyReq) (*AlipayCommonResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AlipayAgreementModify not implemented")
}
func (UnimplementedPaymentServer) WechatUnifiedOrder(context.Context, *AlipayPageSignReq) (*WxUnifiedPayReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WechatUnifiedOrder not implemented")
}
func (UnimplementedPaymentServer) WechatRefundOrder(context.Context, *WechatRefundOrderReq) (*CreateRefundResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WechatRefundOrder not implemented")
}
func (UnimplementedPaymentServer) WechatPayH5Order(context.Context, *AlipayPageSignReq) (*WxH5PayReplay, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WechatPayH5Order not implemented")
}
func (UnimplementedPaymentServer) mustEmbedUnimplementedPaymentServer() {}

// UnsafePaymentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentServer will
// result in compilation errors.
type UnsafePaymentServer interface {
	mustEmbedUnimplementedPaymentServer()
}

func RegisterPaymentServer(s grpc.ServiceRegistrar, srv PaymentServer) {
	s.RegisterService(&Payment_ServiceDesc, srv)
}

func _Payment_OrderPay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderPayReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).OrderPay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payment_OrderPay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).OrderPay(ctx, req.(*OrderPayReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payment_ClosePayOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClosePayOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).ClosePayOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payment_ClosePayOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).ClosePayOrder(ctx, req.(*ClosePayOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payment_AlipayFundTransUniTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlipayFundTransUniTransferReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).AlipayFundTransUniTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payment_AlipayFundTransUniTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).AlipayFundTransUniTransfer(ctx, req.(*AlipayFundTransUniTransferReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payment_OrderStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).OrderStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payment_OrderStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).OrderStatus(ctx, req.(*OrderStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payment_AlipayCheckAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlipayCheckAccountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).AlipayCheckAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payment_AlipayCheckAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).AlipayCheckAccount(ctx, req.(*AlipayCheckAccountReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payment_DyOrderRefund_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DyOrderRefundReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).DyOrderRefund(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payment_DyOrderRefund_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).DyOrderRefund(ctx, req.(*DyOrderRefundReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payment_AlipayTrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlipayTradeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).AlipayTrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payment_AlipayTrade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).AlipayTrade(ctx, req.(*AlipayTradeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payment_AlipayPagePayAndSign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlipayPageSignReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).AlipayPagePayAndSign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payment_AlipayPagePayAndSign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).AlipayPagePayAndSign(ctx, req.(*AlipayPageSignReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payment_AlipayPageUnSign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlipayPageUnSignReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).AlipayPageUnSign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payment_AlipayPageUnSign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).AlipayPageUnSign(ctx, req.(*AlipayPageUnSignReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payment_AlipayCreateRefund_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlipayRefundReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).AlipayCreateRefund(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payment_AlipayCreateRefund_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).AlipayCreateRefund(ctx, req.(*AlipayRefundReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payment_AlipayRefund_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlipayRefundReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).AlipayRefund(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payment_AlipayRefund_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).AlipayRefund(ctx, req.(*AlipayRefundReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payment_AlipayTradePay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlipayTradePayReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).AlipayTradePay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payment_AlipayTradePay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).AlipayTradePay(ctx, req.(*AlipayTradePayReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payment_AlipayAgreementModify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlipayAgreementModifyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).AlipayAgreementModify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payment_AlipayAgreementModify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).AlipayAgreementModify(ctx, req.(*AlipayAgreementModifyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payment_WechatUnifiedOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlipayPageSignReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).WechatUnifiedOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payment_WechatUnifiedOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).WechatUnifiedOrder(ctx, req.(*AlipayPageSignReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payment_WechatRefundOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WechatRefundOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).WechatRefundOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payment_WechatRefundOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).WechatRefundOrder(ctx, req.(*WechatRefundOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payment_WechatPayH5Order_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlipayPageSignReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).WechatPayH5Order(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payment_WechatPayH5Order_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).WechatPayH5Order(ctx, req.(*AlipayPageSignReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Payment_ServiceDesc is the grpc.ServiceDesc for Payment service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Payment_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "payment.Payment",
	HandlerType: (*PaymentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OrderPay",
			Handler:    _Payment_OrderPay_Handler,
		},
		{
			MethodName: "ClosePayOrder",
			Handler:    _Payment_ClosePayOrder_Handler,
		},
		{
			MethodName: "AlipayFundTransUniTransfer",
			Handler:    _Payment_AlipayFundTransUniTransfer_Handler,
		},
		{
			MethodName: "OrderStatus",
			Handler:    _Payment_OrderStatus_Handler,
		},
		{
			MethodName: "AlipayCheckAccount",
			Handler:    _Payment_AlipayCheckAccount_Handler,
		},
		{
			MethodName: "DyOrderRefund",
			Handler:    _Payment_DyOrderRefund_Handler,
		},
		{
			MethodName: "AlipayTrade",
			Handler:    _Payment_AlipayTrade_Handler,
		},
		{
			MethodName: "AlipayPagePayAndSign",
			Handler:    _Payment_AlipayPagePayAndSign_Handler,
		},
		{
			MethodName: "AlipayPageUnSign",
			Handler:    _Payment_AlipayPageUnSign_Handler,
		},
		{
			MethodName: "AlipayCreateRefund",
			Handler:    _Payment_AlipayCreateRefund_Handler,
		},
		{
			MethodName: "AlipayRefund",
			Handler:    _Payment_AlipayRefund_Handler,
		},
		{
			MethodName: "AlipayTradePay",
			Handler:    _Payment_AlipayTradePay_Handler,
		},
		{
			MethodName: "AlipayAgreementModify",
			Handler:    _Payment_AlipayAgreementModify_Handler,
		},
		{
			MethodName: "WechatUnifiedOrder",
			Handler:    _Payment_WechatUnifiedOrder_Handler,
		},
		{
			MethodName: "WechatRefundOrder",
			Handler:    _Payment_WechatRefundOrder_Handler,
		},
		{
			MethodName: "WechatPayH5Order",
			Handler:    _Payment_WechatPayH5Order_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payment.proto",
}
