// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: payment.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//支付方式枚举
type PayType int32

const (
	PayType_AlipayWap  PayType = 0 //支付宝wap支付
	PayType_WxUniApp   PayType = 1 //微信小程序支付
	PayType_TiktokEc   PayType = 2 //头条小程序支付
	PayType_AlipayWeb  PayType = 3 //支付宝web支付
	PayType_WxWeb      PayType = 4 //微信web支付
	PayType_KsUniAppWx PayType = 5 //快手小程序支付-微信
)

// Enum value maps for PayType.
var (
	PayType_name = map[int32]string{
		0: "AlipayWap",
		1: "WxUniApp",
		2: "TiktokEc",
		3: "AlipayWeb",
		4: "WxWeb",
		5: "KsUniAppWx",
	}
	PayType_value = map[string]int32{
		"AlipayWap":  0,
		"WxUniApp":   1,
		"TiktokEc":   2,
		"AlipayWeb":  3,
		"WxWeb":      4,
		"KsUniAppWx": 5,
	}
)

func (x PayType) Enum() *PayType {
	p := new(PayType)
	*p = x
	return p
}

func (x PayType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PayType) Descriptor() protoreflect.EnumDescriptor {
	return file_payment_proto_enumTypes[0].Descriptor()
}

func (PayType) Type() protoreflect.EnumType {
	return &file_payment_proto_enumTypes[0]
}

func (x PayType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PayType.Descriptor instead.
func (PayType) EnumDescriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{0}
}

//创建支付订单
type OrderPayReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppPkgName string  `protobuf:"bytes,1,opt,name=AppPkgName,proto3" json:"AppPkgName,omitempty"`                 //应用包名
	OrderSn    string  `protobuf:"bytes,2,opt,name=OrderSn,proto3" json:"OrderSn,omitempty"`                       //唯一订单号
	Amount     int64   `protobuf:"varint,3,opt,name=Amount,proto3" json:"Amount,omitempty"`                        //订单金额，单位分
	Subject    string  `protobuf:"bytes,4,opt,name=Subject,proto3" json:"Subject,omitempty"`                       //订单标题
	PayType    PayType `protobuf:"varint,5,opt,name=PayType,proto3,enum=payment.PayType" json:"PayType,omitempty"` //支付方式
	NotifyURL  string  `protobuf:"bytes,6,opt,name=NotifyURL,proto3" json:"NotifyURL,omitempty"`                   //回调通知地址
	ReturnURL  string  `protobuf:"bytes,7,opt,name=returnURL,proto3" json:"returnURL,omitempty"`                   //H5,wap支付跳转地址
	WxOpenID   string  `protobuf:"bytes,8,opt,name=WxOpenID,proto3" json:"WxOpenID,omitempty"`                     //微信小程序支付时必传
}

func (x *OrderPayReq) Reset() {
	*x = OrderPayReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payment_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderPayReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderPayReq) ProtoMessage() {}

func (x *OrderPayReq) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderPayReq.ProtoReflect.Descriptor instead.
func (*OrderPayReq) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{0}
}

func (x *OrderPayReq) GetAppPkgName() string {
	if x != nil {
		return x.AppPkgName
	}
	return ""
}

func (x *OrderPayReq) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *OrderPayReq) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *OrderPayReq) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *OrderPayReq) GetPayType() PayType {
	if x != nil {
		return x.PayType
	}
	return PayType_AlipayWap
}

func (x *OrderPayReq) GetNotifyURL() string {
	if x != nil {
		return x.NotifyURL
	}
	return ""
}

func (x *OrderPayReq) GetReturnURL() string {
	if x != nil {
		return x.ReturnURL
	}
	return ""
}

func (x *OrderPayReq) GetWxOpenID() string {
	if x != nil {
		return x.WxOpenID
	}
	return ""
}

//创建支付订单返回
type OrderPayResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderSn   string            `protobuf:"bytes,1,opt,name=OrderSn,proto3" json:"OrderSn,omitempty"`                       //商户唯一订单号
	PayType   PayType           `protobuf:"varint,6,opt,name=PayType,proto3,enum=payment.PayType" json:"PayType,omitempty"` //支付方式
	AlipayWap string            `protobuf:"bytes,3,opt,name=AlipayWap,proto3" json:"AlipayWap,omitempty"`                   //支付宝wap支付
	WxUniApp  *WxUniAppPayReply `protobuf:"bytes,4,opt,name=WxUniApp,proto3" json:"WxUniApp,omitempty"`                     //微信小程序支付
	TikTokEc  *TiktokEcPayReply `protobuf:"bytes,5,opt,name=TikTokEc,proto3" json:"TikTokEc,omitempty"`                     //抖音小程序支付
	AlipayWeb string            `protobuf:"bytes,7,opt,name=AlipayWeb,proto3" json:"AlipayWeb,omitempty"`                   //支付宝web支付
	WxNative  *WxNativePayReply `protobuf:"bytes,8,opt,name=WxNative,proto3" json:"WxNative,omitempty"`                     //微信web支付
	KsUniApp  *KsUniAppReply    `protobuf:"bytes,9,opt,name=KsUniApp,proto3" json:"KsUniApp,omitempty"`                     //快手小程序
}

func (x *OrderPayResp) Reset() {
	*x = OrderPayResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payment_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderPayResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderPayResp) ProtoMessage() {}

func (x *OrderPayResp) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderPayResp.ProtoReflect.Descriptor instead.
func (*OrderPayResp) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{1}
}

func (x *OrderPayResp) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *OrderPayResp) GetPayType() PayType {
	if x != nil {
		return x.PayType
	}
	return PayType_AlipayWap
}

func (x *OrderPayResp) GetAlipayWap() string {
	if x != nil {
		return x.AlipayWap
	}
	return ""
}

func (x *OrderPayResp) GetWxUniApp() *WxUniAppPayReply {
	if x != nil {
		return x.WxUniApp
	}
	return nil
}

func (x *OrderPayResp) GetTikTokEc() *TiktokEcPayReply {
	if x != nil {
		return x.TikTokEc
	}
	return nil
}

func (x *OrderPayResp) GetAlipayWeb() string {
	if x != nil {
		return x.AlipayWeb
	}
	return ""
}

func (x *OrderPayResp) GetWxNative() *WxNativePayReply {
	if x != nil {
		return x.WxNative
	}
	return nil
}

func (x *OrderPayResp) GetKsUniApp() *KsUniAppReply {
	if x != nil {
		return x.KsUniApp
	}
	return nil
}

//微信uniapp支付返回
type WxUniAppPayReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderInfo string `protobuf:"bytes,1,opt,name=OrderInfo,proto3" json:"OrderInfo,omitempty"` //订单信息的json
	TimeStamp string `protobuf:"bytes,2,opt,name=TimeStamp,proto3" json:"TimeStamp,omitempty"` //生成订单时间
	NonceStr  string `protobuf:"bytes,3,opt,name=NonceStr,proto3" json:"NonceStr,omitempty"`   //用于验签的随机串
	Package   string `protobuf:"bytes,4,opt,name=Package,proto3" json:"Package,omitempty"`     //"prepay_id="+预支付交易会话标识
	SignType  string `protobuf:"bytes,5,opt,name=SignType,proto3" json:"SignType,omitempty"`   //签名方式
	PaySign   string `protobuf:"bytes,6,opt,name=PaySign,proto3" json:"PaySign,omitempty"`     //支付签名
	OrderSn   string `protobuf:"bytes,7,opt,name=OrderSn,proto3" json:"OrderSn,omitempty"`     //商户订单号
}

func (x *WxUniAppPayReply) Reset() {
	*x = WxUniAppPayReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payment_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WxUniAppPayReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WxUniAppPayReply) ProtoMessage() {}

func (x *WxUniAppPayReply) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WxUniAppPayReply.ProtoReflect.Descriptor instead.
func (*WxUniAppPayReply) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{2}
}

func (x *WxUniAppPayReply) GetOrderInfo() string {
	if x != nil {
		return x.OrderInfo
	}
	return ""
}

func (x *WxUniAppPayReply) GetTimeStamp() string {
	if x != nil {
		return x.TimeStamp
	}
	return ""
}

func (x *WxUniAppPayReply) GetNonceStr() string {
	if x != nil {
		return x.NonceStr
	}
	return ""
}

func (x *WxUniAppPayReply) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *WxUniAppPayReply) GetSignType() string {
	if x != nil {
		return x.SignType
	}
	return ""
}

func (x *WxUniAppPayReply) GetPaySign() string {
	if x != nil {
		return x.PaySign
	}
	return ""
}

func (x *WxUniAppPayReply) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

type WxNativePayReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CodeUrl    string `protobuf:"bytes,1,opt,name=CodeUrl,proto3" json:"CodeUrl,omitempty"`       //二维码链接
	CodeBase64 string `protobuf:"bytes,2,opt,name=CodeBase64,proto3" json:"CodeBase64,omitempty"` //二维码的base64
}

func (x *WxNativePayReply) Reset() {
	*x = WxNativePayReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payment_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WxNativePayReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WxNativePayReply) ProtoMessage() {}

func (x *WxNativePayReply) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WxNativePayReply.ProtoReflect.Descriptor instead.
func (*WxNativePayReply) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{3}
}

func (x *WxNativePayReply) GetCodeUrl() string {
	if x != nil {
		return x.CodeUrl
	}
	return ""
}

func (x *WxNativePayReply) GetCodeBase64() string {
	if x != nil {
		return x.CodeBase64
	}
	return ""
}

//抖音小程序支付返回
type TiktokEcPayReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId    string `protobuf:"bytes,1,opt,name=OrderId,proto3" json:"OrderId,omitempty"`       //抖音侧唯一订单号
	OrderToken string `protobuf:"bytes,2,opt,name=OrderToken,proto3" json:"OrderToken,omitempty"` //签名后的订单信息
}

func (x *TiktokEcPayReply) Reset() {
	*x = TiktokEcPayReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payment_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TiktokEcPayReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TiktokEcPayReply) ProtoMessage() {}

func (x *TiktokEcPayReply) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TiktokEcPayReply.ProtoReflect.Descriptor instead.
func (*TiktokEcPayReply) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{4}
}

func (x *TiktokEcPayReply) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *TiktokEcPayReply) GetOrderToken() string {
	if x != nil {
		return x.OrderToken
	}
	return ""
}

//快手小程序支付 返回
type KsUniAppReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderNo        string `protobuf:"bytes,1,opt,name=OrderNo,proto3" json:"OrderNo,omitempty"`               //订单号
	OrderInfoToken string `protobuf:"bytes,2,opt,name=OrderInfoToken,proto3" json:"OrderInfoToken,omitempty"` //订单token
}

func (x *KsUniAppReply) Reset() {
	*x = KsUniAppReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payment_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KsUniAppReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KsUniAppReply) ProtoMessage() {}

func (x *KsUniAppReply) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KsUniAppReply.ProtoReflect.Descriptor instead.
func (*KsUniAppReply) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{5}
}

func (x *KsUniAppReply) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *KsUniAppReply) GetOrderInfoToken() string {
	if x != nil {
		return x.OrderInfoToken
	}
	return ""
}

//关闭微信订单
type ClosePayOrderReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderSn    string  `protobuf:"bytes,1,opt,name=OrderSn,proto3" json:"OrderSn,omitempty"`                       //商户订单号
	PayType    PayType `protobuf:"varint,2,opt,name=PayType,proto3,enum=payment.PayType" json:"PayType,omitempty"` //支付方式
	AppPkgName string  `protobuf:"bytes,3,opt,name=AppPkgName,proto3" json:"AppPkgName,omitempty"`                 //应用包名
}

func (x *ClosePayOrderReq) Reset() {
	*x = ClosePayOrderReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payment_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClosePayOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClosePayOrderReq) ProtoMessage() {}

func (x *ClosePayOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClosePayOrderReq.ProtoReflect.Descriptor instead.
func (*ClosePayOrderReq) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{6}
}

func (x *ClosePayOrderReq) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *ClosePayOrderReq) GetPayType() PayType {
	if x != nil {
		return x.PayType
	}
	return PayType_AlipayWap
}

func (x *ClosePayOrderReq) GetAppPkgName() string {
	if x != nil {
		return x.AppPkgName
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payment_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{7}
}

//查询订单状态req
type OrderStatusReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderSn    string  `protobuf:"bytes,1,opt,name=OrderSn,proto3" json:"OrderSn,omitempty"`                       //商户订单号
	PayType    PayType `protobuf:"varint,2,opt,name=PayType,proto3,enum=payment.PayType" json:"PayType,omitempty"` //支付方式
	AppPkgName string  `protobuf:"bytes,3,opt,name=AppPkgName,proto3" json:"AppPkgName,omitempty"`                 //应用包名
}

func (x *OrderStatusReq) Reset() {
	*x = OrderStatusReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payment_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderStatusReq) ProtoMessage() {}

func (x *OrderStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderStatusReq.ProtoReflect.Descriptor instead.
func (*OrderStatusReq) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{8}
}

func (x *OrderStatusReq) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *OrderStatusReq) GetPayType() PayType {
	if x != nil {
		return x.PayType
	}
	return PayType_AlipayWap
}

func (x *OrderStatusReq) GetAppPkgName() string {
	if x != nil {
		return x.AppPkgName
	}
	return ""
}

//查询订单状态resp
type OrderStatusResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderSn       string `protobuf:"bytes,1,opt,name=OrderSn,proto3" json:"OrderSn,omitempty"`             //商户订单号
	Status        int64  `protobuf:"varint,2,opt,name=Status,proto3" json:"Status,omitempty"`              //支付状态 1支付成功  0其他
	PayAmount     int64  `protobuf:"varint,3,opt,name=PayAmount,proto3" json:"PayAmount,omitempty"`        //支付金额 单位分
	ThirdRespJson string `protobuf:"bytes,4,opt,name=ThirdRespJson,proto3" json:"ThirdRespJson,omitempty"` //第三方支付请求返回json
}

func (x *OrderStatusResp) Reset() {
	*x = OrderStatusResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payment_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderStatusResp) ProtoMessage() {}

func (x *OrderStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderStatusResp.ProtoReflect.Descriptor instead.
func (*OrderStatusResp) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{9}
}

func (x *OrderStatusResp) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *OrderStatusResp) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *OrderStatusResp) GetPayAmount() int64 {
	if x != nil {
		return x.PayAmount
	}
	return 0
}

func (x *OrderStatusResp) GetThirdRespJson() string {
	if x != nil {
		return x.ThirdRespJson
	}
	return ""
}

type AlipayFundTransUniTransferReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderSn        string     `protobuf:"bytes,1,opt,name=OrderSn,proto3" json:"OrderSn,omitempty"`               //商户唯一订单号
	TransAmount    string     `protobuf:"bytes,2,opt,name=TransAmount,proto3" json:"TransAmount,omitempty"`       // 订单总金额，单位为元，精确到小数点后两位，STD_RED_PACKET 产品取值范围[0.01,100000000]； TRANS_ACCOUNT_NO_PWD产品取值范围[0.1,100000000]
	ProductCode    string     `protobuf:"bytes,3,opt,name=ProductCode,proto3" json:"ProductCode,omitempty"`       //业务产品码， 收发现金红包固定为：STD_RED_PACKET； 单笔无密转账到支付宝账户固定为：TRANS_ACCOUNT_NO_PWD； 单笔无密转账到银行卡固定为：TRANS_BANKCARD_NO_PWD
	OrderTitle     string     `protobuf:"bytes,4,opt,name=OrderTitle,proto3" json:"OrderTitle,omitempty"`         //转账业务的标题，用于在支付宝用户的账单里显示
	PayeeInfo      *PayeeInfo `protobuf:"bytes,5,opt,name=payeeInfo,proto3" json:"payeeInfo,omitempty"`           //支付
	BizScene       string     `protobuf:"bytes,6,opt,name=BizScene,proto3" json:"BizScene,omitempty"`             //描述特定的业务场景，可传的参数如下： PERSONAL_COLLECTION：C2C现金红包-领红包； DIRECT_TRANSFER：B2C现金红包、单笔无密转账到支付宝/银行卡
	BusinessParams string     `protobuf:"bytes,7,opt,name=BusinessParams,proto3" json:"BusinessParams,omitempty"` //转账业务请求的扩展参数，支持传入的扩展参数如下： 1、sub_biz_scene 子业务场景，红包业务必传，取值REDPACKET，C2C现金红包、B2C现金红包均需传入； 2、withdraw_timeliness为转账到银行卡的预期到账时间，可选（不传入则默认为T1），取值T0表示预期T+0到账，取值T1表示预期T+1到账，因到账时效受银行机构处理影响，支付宝无法保证一定是T0或者T1到账；
	Remark         string     `protobuf:"bytes,8,opt,name=Remark,proto3" json:"Remark,omitempty"`                 //业务备注
	AppPkgName     string     `protobuf:"bytes,9,opt,name=AppPkgName,proto3" json:"AppPkgName,omitempty"`         //应用包名
}

func (x *AlipayFundTransUniTransferReq) Reset() {
	*x = AlipayFundTransUniTransferReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payment_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlipayFundTransUniTransferReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlipayFundTransUniTransferReq) ProtoMessage() {}

func (x *AlipayFundTransUniTransferReq) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlipayFundTransUniTransferReq.ProtoReflect.Descriptor instead.
func (*AlipayFundTransUniTransferReq) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{10}
}

func (x *AlipayFundTransUniTransferReq) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *AlipayFundTransUniTransferReq) GetTransAmount() string {
	if x != nil {
		return x.TransAmount
	}
	return ""
}

func (x *AlipayFundTransUniTransferReq) GetProductCode() string {
	if x != nil {
		return x.ProductCode
	}
	return ""
}

func (x *AlipayFundTransUniTransferReq) GetOrderTitle() string {
	if x != nil {
		return x.OrderTitle
	}
	return ""
}

func (x *AlipayFundTransUniTransferReq) GetPayeeInfo() *PayeeInfo {
	if x != nil {
		return x.PayeeInfo
	}
	return nil
}

func (x *AlipayFundTransUniTransferReq) GetBizScene() string {
	if x != nil {
		return x.BizScene
	}
	return ""
}

func (x *AlipayFundTransUniTransferReq) GetBusinessParams() string {
	if x != nil {
		return x.BusinessParams
	}
	return ""
}

func (x *AlipayFundTransUniTransferReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *AlipayFundTransUniTransferReq) GetAppPkgName() string {
	if x != nil {
		return x.AppPkgName
	}
	return ""
}

type PayeeInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identity     string `protobuf:"bytes,1,opt,name=Identity,proto3" json:"Identity,omitempty"`         //参与方的唯一标识
	IdentityType string `protobuf:"bytes,2,opt,name=IdentityType,proto3" json:"IdentityType,omitempty"` //参与方的标识类型，目前支持如下类型： 1、ALIPAY_USER_ID 支付宝的会员ID 2、ALIPAY_LOGON_ID：支付宝登录号，支持邮箱和手机号格式
	Name         string `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`                 //参与方真实姓名，如果非空，将校验收款支付宝账号姓名一致性。当identity_type=ALIPAY_LOGON_ID时，本字段必填。
}

func (x *PayeeInfo) Reset() {
	*x = PayeeInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payment_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PayeeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayeeInfo) ProtoMessage() {}

func (x *PayeeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayeeInfo.ProtoReflect.Descriptor instead.
func (*PayeeInfo) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{11}
}

func (x *PayeeInfo) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *PayeeInfo) GetIdentityType() string {
	if x != nil {
		return x.IdentityType
	}
	return ""
}

func (x *PayeeInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AlipayCheckAccountReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Account    string `protobuf:"bytes,2,opt,name=Account,proto3" json:"Account,omitempty"`
	AppPkgName string `protobuf:"bytes,3,opt,name=AppPkgName,proto3" json:"AppPkgName,omitempty"`
	UserId     int64  `protobuf:"varint,4,opt,name=UserId,proto3" json:"UserId,omitempty"`
}

func (x *AlipayCheckAccountReq) Reset() {
	*x = AlipayCheckAccountReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payment_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlipayCheckAccountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlipayCheckAccountReq) ProtoMessage() {}

func (x *AlipayCheckAccountReq) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlipayCheckAccountReq.ProtoReflect.Descriptor instead.
func (*AlipayCheckAccountReq) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{12}
}

func (x *AlipayCheckAccountReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AlipayCheckAccountReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *AlipayCheckAccountReq) GetAppPkgName() string {
	if x != nil {
		return x.AppPkgName
	}
	return ""
}

func (x *AlipayCheckAccountReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type AlipayCheckAccountResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64  `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Desc   string `protobuf:"bytes,2,opt,name=Desc,proto3" json:"Desc,omitempty"`
}

func (x *AlipayCheckAccountResp) Reset() {
	*x = AlipayCheckAccountResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payment_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlipayCheckAccountResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlipayCheckAccountResp) ProtoMessage() {}

func (x *AlipayCheckAccountResp) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlipayCheckAccountResp.ProtoReflect.Descriptor instead.
func (*AlipayCheckAccountResp) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{13}
}

func (x *AlipayCheckAccountResp) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AlipayCheckAccountResp) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

var File_payment_proto protoreflect.FileDescriptor

var file_payment_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0xfd, 0x01, 0x0a, 0x0b, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x50, 0x61, 0x79, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x41, 0x70, 0x70, 0x50,
	0x6b, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x41, 0x70,
	0x70, 0x50, 0x6b, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x53, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x53, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x75,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x53, 0x75, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x12, 0x2a, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e,
	0x50, 0x61, 0x79, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x50, 0x61, 0x79, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x55, 0x52, 0x4c, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x55, 0x52, 0x4c, 0x12, 0x1c,
	0x0a, 0x09, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x55, 0x52, 0x4c, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x55, 0x52, 0x4c, 0x12, 0x1a, 0x0a, 0x08,
	0x57, 0x78, 0x4f, 0x70, 0x65, 0x6e, 0x49, 0x44, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x57, 0x78, 0x4f, 0x70, 0x65, 0x6e, 0x49, 0x44, 0x22, 0xe9, 0x02, 0x0a, 0x0c, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x50, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x53, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x53, 0x6e, 0x12, 0x2a, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x54, 0x79, 0x70, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x50,
	0x61, 0x79, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x50, 0x61, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x41, 0x6c, 0x69, 0x70, 0x61, 0x79, 0x57, 0x61, 0x70, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x41, 0x6c, 0x69, 0x70, 0x61, 0x79, 0x57, 0x61, 0x70, 0x12, 0x35, 0x0a,
	0x08, 0x57, 0x78, 0x55, 0x6e, 0x69, 0x41, 0x70, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x57, 0x78, 0x55, 0x6e, 0x69, 0x41,
	0x70, 0x70, 0x50, 0x61, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x08, 0x57, 0x78, 0x55, 0x6e,
	0x69, 0x41, 0x70, 0x70, 0x12, 0x35, 0x0a, 0x08, 0x54, 0x69, 0x6b, 0x54, 0x6f, 0x6b, 0x45, 0x63,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74,
	0x2e, 0x54, 0x69, 0x6b, 0x74, 0x6f, 0x6b, 0x45, 0x63, 0x50, 0x61, 0x79, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x52, 0x08, 0x54, 0x69, 0x6b, 0x54, 0x6f, 0x6b, 0x45, 0x63, 0x12, 0x1c, 0x0a, 0x09, 0x41,
	0x6c, 0x69, 0x70, 0x61, 0x79, 0x57, 0x65, 0x62, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x41, 0x6c, 0x69, 0x70, 0x61, 0x79, 0x57, 0x65, 0x62, 0x12, 0x35, 0x0a, 0x08, 0x57, 0x78, 0x4e,
	0x61, 0x74, 0x69, 0x76, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x61,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x57, 0x78, 0x4e, 0x61, 0x74, 0x69, 0x76, 0x65, 0x50, 0x61,
	0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x08, 0x57, 0x78, 0x4e, 0x61, 0x74, 0x69, 0x76, 0x65,
	0x12, 0x32, 0x0a, 0x08, 0x4b, 0x73, 0x55, 0x6e, 0x69, 0x41, 0x70, 0x70, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x4b, 0x73, 0x55,
	0x6e, 0x69, 0x41, 0x70, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x08, 0x4b, 0x73, 0x55, 0x6e,
	0x69, 0x41, 0x70, 0x70, 0x22, 0xd4, 0x01, 0x0a, 0x10, 0x57, 0x78, 0x55, 0x6e, 0x69, 0x41, 0x70,
	0x70, 0x50, 0x61, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x53,
	0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x54, 0x69, 0x6d, 0x65,
	0x53, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x53, 0x74,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x53, 0x74,
	0x72, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x53,
	0x69, 0x67, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x53,
	0x69, 0x67, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x53, 0x69,
	0x67, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x50, 0x61, 0x79, 0x53, 0x69, 0x67,
	0x6e, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x6e, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x6e, 0x22, 0x4c, 0x0a, 0x10, 0x57,
	0x78, 0x4e, 0x61, 0x74, 0x69, 0x76, 0x65, 0x50, 0x61, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x18, 0x0a, 0x07, 0x43, 0x6f, 0x64, 0x65, 0x55, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x43, 0x6f, 0x64, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x6f, 0x64,
	0x65, 0x42, 0x61, 0x73, 0x65, 0x36, 0x34, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x43,
	0x6f, 0x64, 0x65, 0x42, 0x61, 0x73, 0x65, 0x36, 0x34, 0x22, 0x4c, 0x0a, 0x10, 0x54, 0x69, 0x6b,
	0x74, 0x6f, 0x6b, 0x45, 0x63, 0x50, 0x61, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a,
	0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x51, 0x0a, 0x0d, 0x4b, 0x73, 0x55, 0x6e, 0x69,
	0x41, 0x70, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x4e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x4e, 0x6f, 0x12, 0x26, 0x0a, 0x0e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x78, 0x0a, 0x10, 0x43, 0x6c,
	0x6f, 0x73, 0x65, 0x50, 0x61, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x18,
	0x0a, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x6e, 0x12, 0x2a, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x70, 0x61, 0x79, 0x6d,
	0x65, 0x6e, 0x74, 0x2e, 0x50, 0x61, 0x79, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x50, 0x61, 0x79,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x41, 0x70, 0x70, 0x50, 0x6b, 0x67, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x41, 0x70, 0x70, 0x50, 0x6b, 0x67,
	0x4e, 0x61, 0x6d, 0x65, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x76, 0x0a,
	0x0e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x12,
	0x18, 0x0a, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x6e, 0x12, 0x2a, 0x0a, 0x07, 0x50, 0x61, 0x79,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x70, 0x61, 0x79,
	0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x50, 0x61, 0x79, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x50, 0x61,
	0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x41, 0x70, 0x70, 0x50, 0x6b, 0x67, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x41, 0x70, 0x70, 0x50, 0x6b,
	0x67, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x87, 0x01, 0x0a, 0x0f, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x53, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x53, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x50,
	0x61, 0x79, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x50, 0x61, 0x79, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x54, 0x68, 0x69,
	0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x4a, 0x73, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x54, 0x68, 0x69, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x4a, 0x73, 0x6f, 0x6e, 0x22,
	0xcb, 0x02, 0x0a, 0x1d, 0x41, 0x6c, 0x69, 0x70, 0x61, 0x79, 0x46, 0x75, 0x6e, 0x64, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x55, 0x6e, 0x69, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x20, 0x0a,
	0x0b, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x1e, 0x0a, 0x0a, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12,
	0x30, 0x0a, 0x09, 0x70, 0x61, 0x79, 0x65, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x50, 0x61, 0x79,
	0x65, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x70, 0x61, 0x79, 0x65, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x42, 0x69, 0x7a, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x42, 0x69, 0x7a, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x12, 0x26, 0x0a,
	0x0e, 0x42, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x42, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x12, 0x1e, 0x0a,
	0x0a, 0x41, 0x70, 0x70, 0x50, 0x6b, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x41, 0x70, 0x70, 0x50, 0x6b, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x5f, 0x0a,
	0x09, 0x50, 0x61, 0x79, 0x65, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x49, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x49, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x22, 0x0a, 0x0c, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x49, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x7d,
	0x0a, 0x15, 0x41, 0x6c, 0x69, 0x70, 0x61, 0x79, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x41, 0x70, 0x70, 0x50, 0x6b, 0x67, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x41, 0x70, 0x70, 0x50, 0x6b,
	0x67, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x44, 0x0a,
	0x16, 0x41, 0x6c, 0x69, 0x70, 0x61, 0x79, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x44, 0x65, 0x73, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x44,
	0x65, 0x73, 0x63, 0x2a, 0x5e, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0d,
	0x0a, 0x09, 0x41, 0x6c, 0x69, 0x70, 0x61, 0x79, 0x57, 0x61, 0x70, 0x10, 0x00, 0x12, 0x0c, 0x0a,
	0x08, 0x57, 0x78, 0x55, 0x6e, 0x69, 0x41, 0x70, 0x70, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x54,
	0x69, 0x6b, 0x74, 0x6f, 0x6b, 0x45, 0x63, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x41, 0x6c, 0x69,
	0x70, 0x61, 0x79, 0x57, 0x65, 0x62, 0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x57, 0x78, 0x57, 0x65,
	0x62, 0x10, 0x04, 0x12, 0x0e, 0x0a, 0x0a, 0x4b, 0x73, 0x55, 0x6e, 0x69, 0x41, 0x70, 0x70, 0x57,
	0x78, 0x10, 0x05, 0x32, 0xed, 0x02, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x12,
	0x37, 0x0a, 0x08, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x50, 0x61, 0x79, 0x12, 0x14, 0x2e, 0x70, 0x61,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x50, 0x61, 0x79, 0x52, 0x65,
	0x71, 0x1a, 0x15, 0x2e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x50, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3a, 0x0a, 0x0d, 0x43, 0x6c, 0x6f, 0x73,
	0x65, 0x50, 0x61, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x19, 0x2e, 0x70, 0x61, 0x79, 0x6d,
	0x65, 0x6e, 0x74, 0x2e, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x50, 0x61, 0x79, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x12, 0x54, 0x0a, 0x1a, 0x41, 0x6c, 0x69, 0x70, 0x61, 0x79, 0x46, 0x75,
	0x6e, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x55, 0x6e, 0x69, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66,
	0x65, 0x72, 0x12, 0x26, 0x2e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x41, 0x6c, 0x69,
	0x70, 0x61, 0x79, 0x46, 0x75, 0x6e, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x55, 0x6e, 0x69, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x70, 0x61, 0x79,
	0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x40, 0x0a, 0x0b, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x17, 0x2e, 0x70, 0x61, 0x79, 0x6d,
	0x65, 0x6e, 0x74, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x65, 0x71, 0x1a, 0x18, 0x2e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x55, 0x0a, 0x12,
	0x41, 0x6c, 0x69, 0x70, 0x61, 0x79, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x1e, 0x2e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x41, 0x6c, 0x69,
	0x70, 0x61, 0x79, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x1a, 0x1f, 0x2e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x41, 0x6c, 0x69,
	0x70, 0x61, 0x79, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_payment_proto_rawDescOnce sync.Once
	file_payment_proto_rawDescData = file_payment_proto_rawDesc
)

func file_payment_proto_rawDescGZIP() []byte {
	file_payment_proto_rawDescOnce.Do(func() {
		file_payment_proto_rawDescData = protoimpl.X.CompressGZIP(file_payment_proto_rawDescData)
	})
	return file_payment_proto_rawDescData
}

var file_payment_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_payment_proto_goTypes = []interface{}{
	(PayType)(0),                          // 0: payment.PayType
	(*OrderPayReq)(nil),                   // 1: payment.OrderPayReq
	(*OrderPayResp)(nil),                  // 2: payment.OrderPayResp
	(*WxUniAppPayReply)(nil),              // 3: payment.WxUniAppPayReply
	(*WxNativePayReply)(nil),              // 4: payment.WxNativePayReply
	(*TiktokEcPayReply)(nil),              // 5: payment.TiktokEcPayReply
	(*KsUniAppReply)(nil),                 // 6: payment.KsUniAppReply
	(*ClosePayOrderReq)(nil),              // 7: payment.ClosePayOrderReq
	(*Empty)(nil),                         // 8: payment.Empty
	(*OrderStatusReq)(nil),                // 9: payment.OrderStatusReq
	(*OrderStatusResp)(nil),               // 10: payment.OrderStatusResp
	(*AlipayFundTransUniTransferReq)(nil), // 11: payment.AlipayFundTransUniTransferReq
	(*PayeeInfo)(nil),                     // 12: payment.PayeeInfo
	(*AlipayCheckAccountReq)(nil),         // 13: payment.AlipayCheckAccountReq
	(*AlipayCheckAccountResp)(nil),        // 14: payment.AlipayCheckAccountResp
}
var file_payment_proto_depIdxs = []int32{
	0,  // 0: payment.OrderPayReq.PayType:type_name -> payment.PayType
	0,  // 1: payment.OrderPayResp.PayType:type_name -> payment.PayType
	3,  // 2: payment.OrderPayResp.WxUniApp:type_name -> payment.WxUniAppPayReply
	5,  // 3: payment.OrderPayResp.TikTokEc:type_name -> payment.TiktokEcPayReply
	4,  // 4: payment.OrderPayResp.WxNative:type_name -> payment.WxNativePayReply
	6,  // 5: payment.OrderPayResp.KsUniApp:type_name -> payment.KsUniAppReply
	0,  // 6: payment.ClosePayOrderReq.PayType:type_name -> payment.PayType
	0,  // 7: payment.OrderStatusReq.PayType:type_name -> payment.PayType
	12, // 8: payment.AlipayFundTransUniTransferReq.payeeInfo:type_name -> payment.PayeeInfo
	1,  // 9: payment.Payment.OrderPay:input_type -> payment.OrderPayReq
	7,  // 10: payment.Payment.ClosePayOrder:input_type -> payment.ClosePayOrderReq
	11, // 11: payment.Payment.AlipayFundTransUniTransfer:input_type -> payment.AlipayFundTransUniTransferReq
	9,  // 12: payment.Payment.OrderStatus:input_type -> payment.OrderStatusReq
	13, // 13: payment.Payment.AlipayCheckAccount:input_type -> payment.AlipayCheckAccountReq
	2,  // 14: payment.Payment.OrderPay:output_type -> payment.OrderPayResp
	8,  // 15: payment.Payment.ClosePayOrder:output_type -> payment.Empty
	8,  // 16: payment.Payment.AlipayFundTransUniTransfer:output_type -> payment.Empty
	10, // 17: payment.Payment.OrderStatus:output_type -> payment.OrderStatusResp
	14, // 18: payment.Payment.AlipayCheckAccount:output_type -> payment.AlipayCheckAccountResp
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_payment_proto_init() }
func file_payment_proto_init() {
	if File_payment_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_payment_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderPayReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payment_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderPayResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payment_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WxUniAppPayReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payment_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WxNativePayReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payment_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TiktokEcPayReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payment_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KsUniAppReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payment_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClosePayOrderReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payment_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payment_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderStatusReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payment_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderStatusResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payment_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlipayFundTransUniTransferReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payment_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PayeeInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payment_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlipayCheckAccountReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payment_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlipayCheckAccountResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_payment_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_proto_goTypes,
		DependencyIndexes: file_payment_proto_depIdxs,
		EnumInfos:         file_payment_proto_enumTypes,
		MessageInfos:      file_payment_proto_msgTypes,
	}.Build()
	File_payment_proto = out.File
	file_payment_proto_rawDesc = nil
	file_payment_proto_goTypes = nil
	file_payment_proto_depIdxs = nil
}
